apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy_allow-dns-tenants.yaml
  - networkpolicy_allow-kube-api-tenants.yaml
  - networkpolicy_default-deny-tenants.yaml