apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-telegraf
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      debug=true
      interval = "30s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = "proxmox-telegraf"
      omit_hostname = false

    [[outputs.influxdb_v2]]
      urls = ["http://influxdb-influxdb2.influxdb.svc.cluster.local:80"]
      token = "${INFLUXDB_TOKEN}"
      organization = "crulabs"
      bucket = "pve"

    [[inputs.proxmox]]
      base_url = "${PROXMOX_URL}"
      api_token = "${PROXMOX_API_TOKEN}"
      node_name = "pve"
      insecure_skip_verify = true
