apiVersion: v1
kind: Secret
metadata:
    name: proxmox-telegraf
    namespace: monitoring
stringData:
    influx-token: ENC[AES256_GCM,data:pu0WzSdzPhb/6f4XNlqELCqGqni5pNRBiCb5/k96ITq2DGws2aSSzsBTjTXJHV1Gb/B1cxsBk/SZRUksHWO9Owi2av5J1p9BC27LMU/k3SONNvh2cZVVcw==,iv:DBC/4u3aq/GRqxnAaTOYPMkHRfW0E/bEd1ZdSeAUVIY=,tag:lDY5+iYxoyP4uZcqnL55eg==,type:str]
    api-token: ENC[AES256_GCM,data:bVCSGB4fA/bbr6GRb0zoYZLdguHidOdhaN/v3KH+WXN8Y7336Pi9+YybCAeXur5mRD0ewrdtPHY0WvV3,iv:BDETMjWO+4wdjePobqlgfQ+5NHmw7iqGFKtS16jJXgY=,tag:ZENFfP5aG9WDVHIgcj4wrg==,type:str]
    url: ENC[AES256_GCM,data:P5X5wMv3hSP7bZSI6G/Jc/UGNbBpvModnZ05xj4Z13/27nn1,iv:8eTvqg3PCn/nNll5KwHIfLbjn8HF2qNVOR2AMFnUX8A=,tag:NFNTCcIRM93nB6e1110Cbg==,type:str]
sops:
    lastmodified: "2026-05-01T23:39:51Z"
    mac: ENC[AES256_GCM,data:/ue1xb3w0YOa8T3TIYLkuAiNB8BZhA8Rk6/RjMakkMCuLHR1+V22NR0CU2LZ5ysgUDeraz9Sx2e55b0svhQfIjWEa0JLzafgYUbvxMMxoBrXZXIsNf4QkchfP21LeDUfD5QckYLta8BRYQSTb6nxRJdP5XC5adiUEvkpE8jEdFg=,iv:5jF3GepAYqcqh2pumRoc746cdyyDZNkOmMxkhahvVlE=,tag:e/hd7CVmS7eFudAqMsqt+g==,type:str]
    pgp:
        - created_at: "2026-05-01T23:39:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAlC94XFRnyzPhWIRqGLLcpDnQkcw82fbNb4Jypo2lB7du
            iLUr04r9npojr9IoufScmVtI55DpCs7SJa8YwRKwT1QWT7wWDWxaJF6SE/NH+7nA
            1/GToOWKEZFtxHWMZ6S1aJu3mYYdK6wsKPBvyZtk/AZbrndchsLdUahaOzqS3zt8
            WHyP7x/cY/yCdbtY2oz18VlW5aNDscL1bgcv3gu/XFxdAh5FTj8UkQBrP5RHF51n
            IvrxLxcQ3oSjiAPhEtJqzMLmta+TwD/vG2zlnw+vzirawSdvPEGoyENVLNaKNqoK
            QUOIC4ClXq8bY69TTTo3QuIukhahzhw+713K+DvMaXhFHcQ7Z9W2jaLbmJwSSjvp
            draIG23jMNlfmSfW8JJjzUyYX2T5YXPfu5kI7Q2zHLVF8pM4yoGk37F7HCHGBj0E
            7cCaTmGCTfTgt0kX+cSA1Y5VnFj8WXwWLkz9iCJxlMM6i6vFP/J+995IC/D2VONo
            XwZ/MAJIg1Xta9mUnE43+ER2srPuZxxJ3RkoIblCurEopel47I4R4IDlzHK+Y6o3
            /DAzleJO/3/N977Y32YaXNq1IbLpC9Ac+wG+Dnb9KH8ehMAXcvNCx5JHa1UN8jo9
            xMEcJt06dtFYG2e1TMrkjhbiLnqcM8mpRntai+TADoH9Vuhd3mTWupHvj/W8vCPU
            aAEJAhAFNw001+o6o/d4ryZc6QxDvCvuPOue3nRCD+JRFqHlz6kzJtr/Wu5jgSdX
            jGhoaUQnZ2qttOK2qaRPGllSdJp64hYyQtMqO+dXM83rc9EueIBB0aGh0Msy5W7X
            tt2QBjnuneB3
            =96N3
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
