# metallb-addresspool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: default
spec:
    addresses:
        - ENC[AES256_GCM,data:yO9/9u5ki9aeKH/nYZ8IGV5bBQ==,iv:6LpRr8tQnpT8AhlmOXAd1zXsVmbsDakroHVkkaHU43c=,tag:/lZwaeSPTJ08jPnfgMB/qw==,type:str]
sops:
    lastmodified: "2026-05-26T09:00:52Z"
    mac: ENC[AES256_GCM,data:0CHj1ljeHB5tupb5YEG0cJMxfazFEYuamQseIz1odBQVA1X2Qh0RMaq6jbN8sXZHI0CbdO3XvXXa0zGZfYjSay04ZZF0HrXu+XnhiXa1RyuBzxYFJXqu1I7S53uTCibFJsm0inZ2tsJOyw34WPNfkJ+78sqvBTkhwuucH/fKe0A=,iv:fVhRiyYskzmFKpSgZ4C0SxH6uhHbkuRwagsfbtLoyE0=,tag:rKLLBFRSJDCy5bAfXxImIg==,type:str]
    pgp:
        - created_at: "2026-05-26T09:00:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAlUuDyGFiKgJkIqraU/Ibt3BZzwArXdHCFSdq09Br1NPU
            kn9vCZ8Xfnuvibet/DDlDiTVIbOqui5VPS5rx3Uj5SuTVJdhpypWNR+H/40AdoMm
            5dCv1S4B797fbZUGAKc6KpK473fH9y4f1DdyhU4g4H2LFZkO0NvQPBRdSQoxse6r
            YxO/YtwzyGiYgQZLpozR+eDaujeDKck3qfNEKuEB/isko7l4Ejr4NVSmbMEkP5H7
            cBcf7/dL81+cbohaZc0SZyFC8/ecoHBAYhk5ijyzpCwh7QzSLlN3l6tMBhFH0PFl
            GIpEjFC9E37tweELjl4tL1+4fvceqHkrMOEy7wSH8Q/f8CUa2hqHZ/1inpjPQdXw
            WD6zkM3P0lnsYhhaHpImhW0Nse4CQeRWAi0GrryG6ldb0MC4cdLP+Ibhgy3J3Oi5
            gXownq6Z1R0sNfrb4DuTLvt8nFveAxLsuziZt3Se7QGzJRT7W7Wswsh+uKibXicr
            0uvUoIOnbKoGQu1XTA6Gq/kU2vNtBjmQeGFYJc1DxUe5xtYhSkI9YCqBR/lIiePI
            jUAeyYmw6jdMOapiR76XwLHQiRWYAOlEF7r3YJE5xz9LULMPZrfqJ1X2E7/61ci3
            eB49Rnja7+CzkHljhTpy5oxnlO/4tSS/GJcGEMPFb1Sp1+7ZAs8Un8LEbtOJcPDU
            aAEJAhBKphLVuRsgTdP6UntXuVHItkd0VO/NrOW9N0p5zZ3FSq1pX8v781+vec2G
            XkBQ9UIfSTSTPfXNPJFauSudN1nMiLJ3iY2X2WD/W+/3h5EryHBKuBD54csbhgAn
            D7MzAQYXZeUV
            =6xH1
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
