---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: crulabs-helm
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/crulabs/helm
  ref:
    branch: main
