apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tenant
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/crulabs/charts/tenant
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "0.3.1"
