apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crulabs-gateway
  namespace: gateway-system
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    protocol: HTTP
    port: 8000
    allowedRoutes:
      namespaces:
        from: All
  - name: websecure
    protocol: HTTPS
    port: 8443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: gateway-tls
        namespace: gateway-system
