apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: gateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: 1.5.0
      sourceRef:
        kind: OCIRepository
        name: nginx-gateway-fabric
        namespace: flux-system
  values:
    service:
      type: NodePort
      httpPort:
        nodePort: 30180
      httpsPort:
        nodePort: 30543

    metrics:
      enable: true
      port: 9113

    nginxGateway:
      productTelemetry:
        enable: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi

    nginx:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
