apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: gateway-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 32.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    # Gateway API Provider aktivieren
    providers:
      kubernetesGateway:
        enabled: true
    
    # Service Konfiguration
    service:
      type: NodePort
      nodePorts:
        web: 30180
        websecure: 30543
    
    ports:
      web:
        port: 8000
        nodePort: 30180
      websecure:
        port: 8443
        nodePort: 30543
      metrics:
        port: 9100
    
    # Metrics für Prometheus
    metrics:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: gateway-system
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
