apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 24h
  url: https://nginx.github.io/nginx-gateway-fabric
