apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: gitea
spec:
  interval: 1h
  chart:
    spec:
      chart: valkey
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: valkey
        namespace: flux-system
  values:
    dataStorage:
      enabled: true
      requestedSize: 1Gi
      className: local-path

    auth:
      enabled: true
      usersExistingSecret: valkey-users
      aclUsers:
        default:
          permissions: "~* &* +@all"
          passwordKey: REDIS_PASSWORD

    replica:
      enabled: true
      replicas: 2
      persistence:
        size: 1Gi
        storageClass: local-path

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
