---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg-cluster
  namespace: gitea
spec:
  interval: 24h
  url: oci://ghcr.io/crulabs/helm/cnpg-cluster
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "1.1.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: cnpg-cluster
    namespace: gitea
  values:
    initdb:
      database: gitea
      secret:
        name: gitea-db-credentials

    storage:
      size: 10Gi

    backup:
      enabled: true

    affinity:
      enablePodAntiAffinity: true
