---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  dependsOn:
    - name: gitea-postgres
      namespace: gitea
    - name: valkey
      namespace: gitea
  chart:
    spec:
      chart: gitea
      version: "12.7.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 24h
  values:
    persistence:
      enabled: true
      size: 10Gi

    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    valkey-cluster:
      enabled: false
    valkey:
      enabled: false

    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      additionalConfigFromEnvs:
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-db-credentials
              key: password
        - name: GITEA__CACHE__HOST
          valueFrom:
            secretKeyRef:
              name: gitea-valkey-connstrings
              key: cache_host
        - name: GITEA__SESSION__PROVIDER_CONFIG
          valueFrom:
            secretKeyRef:
              name: gitea-valkey-connstrings
              key: session_provider_config
        - name: GITEA__QUEUE__CONN_STR
          valueFrom:
            secretKeyRef:
              name: gitea-valkey-connstrings
              key: queue_conn_str
      config:
        server:
          DOMAIN: "gitea.crulabs.intern"
          ROOT_URL: "https://gitea.crulabs.intern"
          LANDING_PAGE: login
        database:
          DB_TYPE: postgres
          HOST: "gitea-postgres-rw.gitea.svc.cluster.local:5432"
          NAME: gitea
          USER: app
        cache:
          ADAPTER: redis
        session:
          PROVIDER: redis
        queue:
          TYPE: redis

    extraVolumes:
      - name: ca-cert
        configMap:
          name: crulabs-ca-cert

    extraContainerVolumeMounts:
      - name: ca-cert
        mountPath: /etc/ssl/certs/crulabs-ca.pem
        subPath: ca.pem
        readOnly: true

    oauth:
      - name: keycloak
        provider: openidConnect
        active: true
        synchronizeUsers: true
        autoDiscoverURL: "https://keycloak.crulabs.intern/auth/realms/crulabs/.well-known/openid-configuration"
        groupClaimName: "groups"
        adminGroup: "gitea-admin"
        existingSecret: gitea-oauth-secret