---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease_postgres.yaml
  - helmrelease_gitea.yaml
  - helmrelease_valkey.yaml
  - obc.yaml
  - secret_gitea-db-credentials.enc.yaml
  - secret_gitea-oauth-secret.enc.yaml
  - secret_valkey-users.enc.yaml
  - secret_gitea-valkey-connstrings.enc.yaml
  - httproute.yaml
  - configmap_ca-cert.yaml
