apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitea-postgres-backups
  namespace: gitea
spec:
  generateBucketName: gitea-postgres-backups
  objectBucketName: obc-gitea-gitea-postgres-backups
  storageClassName: rook-ceph-bucket
