apiVersion: v1
kind: Secret
metadata:
    name: gitea-valkey-connstrings
    namespace: gitea
type: Opaque
stringData:
    cache_host: ENC[AES256_GCM,data:pBI2ynibs6YvP8lH4nsHoD1YhIXPKhGA0NljN+I3K5PT2MIOhfeSg5xO+f0tCby7PTcbT8cSccQLQMEONEFXuEwx,iv:3GBmtLpOSwTgrb2Y689h/wxvBcQcQOVeZIMvfGaL/LA=,tag:CfMwl/KKl62QJT4FO/6W9Q==,type:str]
    session_provider_config: ENC[AES256_GCM,data:FyE51Gs+i8BMfYIPa6tj5W+6o31qsM5dN2i2+q0cjjMWhRbHLOHxwdo5/GF2kQuI44kIXJui63gc2jd+PEbErECtwsB4VX9JPnlsMbeomnxOpq0+v5s/oqJuMOnG1d04fvE=,iv:Vw4mcbMMtEtHAGfev0Wl/GKXnbhZ5V+YQ6sY2ienqfM=,tag:QUHYTivUyOor+nUWRjUfgQ==,type:str]
    queue_conn_str: ENC[AES256_GCM,data:rVMs52OYnEindwOR9ThLVlHoO7rB5+agGzUaR3Q/L479p7AOzA3rj7fu7EAJU2QFUVj65/BgDZb6S3Bkbd/x/r59,iv:DsuuduuC4ADHgmiq8iFotB7fCBcRNjkWXZxqYgycjwo=,tag:/fO0HjQwanCtt+70wWgQNg==,type:str]
sops:
    lastmodified: "2026-07-30T18:17:38Z"
    mac: ENC[AES256_GCM,data:KXLXeHIoeZM8b8ugwp8EY1BAVhIqoNINho4M4PnX49xl/2zPjy9Sld84Hy6oVKI1u9ARmyibT6UCqAoYgK22rgQCkI8yRlJIx5XOrN+wjn6AAjba5KpaP7ZZnT4OSmm6iHjgNH0yNCNrdfYyfHRbyzfb5MF8SjSxUzW2gifZx2M=,iv:bkJYCn3AE8LkHyVqmVrv2ZoItukHj09/Zl/M6JVP0PA=,tag:xh+lUNuJt7Rz0ijiXWA3oQ==,type:str]
    pgp:
        - created_at: "2026-07-30T18:17:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/+Mf+02h9OELR1l4pguX8/4lLEyvGtYmfY1fRziEppjio2
            oXGzrddUaD0fYw8y49o408R1wYXZzR4MThJgsVw1t4yYfUyajNF7a44UTk1cHiML
            wOlYxL+OAJuY6ylzrVak2VW0o5T/2LW5K1ndq81dlFCO0Xb5GVrQz+bxSzI91egu
            rtltPLjs2o3UYrzEm9P6prjwS4mvcr6sy7/AfwNu+9LYk24I4gqUVvafYkXkSsPL
            wB6NJ7kfTDsFkeH8OXCRNxAq2jUZ7Pd+4fTkDYEEe1rU819s9hzOt8x83AqpMeRy
            He9F7d09155j4zGChbPzYGp8X5GJRjH6qfE0LY66WynNY/HD0ZHvySlKZotsxX5g
            ekeBr9dVp63UPX8wAC0PHow9/p9t0HWluQhwGcBgf0N1pJwqW8xd9s8/RrX9eF/R
            MFjTL7Dhs6Jx6jCKA4+ZpO5AlT/hImNZgGDQpdLh0b0SlNQeeZasjMDAC8ABQL5R
            0AvSS9UuV2eiYIemT2NXRx/ZSYZ24H9/as5ZT6YXANO9WaK/5K6s1Krdcb5/Kuk6
            68wVjFUiLFygmRITJ5+MtkIyI9a6kAGWuvJwyuPwvWnKCfOQKCIdi3iJ8E+W1qO1
            5ZPt2rxIw4bktpmU0Z+4LH95R2SeHVuYjfFiFYv0goBgc3GBO+VUVcEA+o4Hjx3U
            ZgEJAhDRASOTkzIe460TGLfn1CREBq6sejBXJCt68IDp1IjAYkjhLmeRx6zt8JbM
            kiDxCeyAk1Y8BxMca4z1FiN8uYhospO/F2gDXTUts+7//4cdO6koQ/4F9Dmzb2/L
            ehtrrYm45A==
            =z1Um
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
