apiVersion: v1
kind: Secret
metadata:
    name: gitea-db-credentials
    namespace: gitea
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Of6N,iv:xNS+ssUzxAG2ldi+bdRyBjqvSWijquCu/MOWats0vfI=,tag:EvItEGuD1db7WwnIBmKnjg==,type:str]
    password: ENC[AES256_GCM,data:ueYNdM5tD50dxbhSStKVXfaV1AWmNUMqzsz2GD9S,iv:eZ1nM2/PsrS1QfYqgKBN54zXiUB5udatkwbejWpQkdc=,tag:U556VdtZi+TbhddRo1HDZA==,type:str]
sops:
    lastmodified: "2026-05-30T12:52:33Z"
    mac: ENC[AES256_GCM,data:L08Hw0F1lttsqA22KgSJtbjsqzY57EWO/xQRUsOKpDU10qqX+sNbrRkajgGsd4EAQ98z8dGDR8dtYxW3ph85MhM8g8N7rTTAkk65dKymvtROpJainuPNkIFs2KuMeJLkpCgx4cU2L1Ub0JcwHjvuWisKVzu8Xf2R/xIYjI1DQkU=,iv:MeffdFaQIoorMbKahE4+H1Ky5ArtY7XWUoPrt1Vn4Ao=,tag:6oifmEPuQjAdjEfxO1MFaQ==,type:str]
    pgp:
        - created_at: "2026-05-30T12:52:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/+LO14y6qnYbK+1Y22hL1ZrFhLO1T0yZiuNCuEdIa+vn3Q
            GDXlJIqT0J8kXuf1TumTCf1+RuGr0W3go5JVUMmWQk93YgIID0fcQnDvVgTN9WJb
            b+16Hguua3iHB0QhLt2bCMfUMxX2NqMBN+r/bpwN5HZ+/Cd7Grh4SWN5OFtUuR8Y
            zmlIAteTI8asbDUwYvEUUtEneeBT6oaaRnA4uhu4zAtB28d1QeBaRqOiLofoUUHo
            Hwh5R86zIXyxEm4KJz+xH4tXXX/cW8Fcml/pVgtHw8bvqNz2cm8HAiKQ/aL+4fb0
            EgboAGfT7KsjBHGYlAtm0PhCE3La7hRWEvnUIh/GPJCnBMilZnAcEAMs4L/FnHm2
            hpWrE2oEyrobNFiJqBLWvEh/siqsWjgzLPuhOvO1I114MymnQZ+4OD9tmQrt60iV
            FzY5+Umi7qsIc17U/IX9984u/030M6NlarmK4/j+IsuTyqY2klX3hxFnqyMo5DDu
            duFlfOJdVWzf11CGrJO2Idb7XmP9ygi1U/weWiyqQxUuV+19SKcYfOFk1hG8j/AD
            xE12WQp64TfD6535dnxys5aII08JxD/QQVdTCYznsrDZEyeLhbY+NyTJ3uYECZsy
            fskRh0FEA4cHxGDbCiZjd+vS7ikQX+526av/JLEMIatPA1biM3f+Cvcvp/Qt1GDU
            aAEJAhAXZU1AB9qwu2XJqxx6v+qo87q0EBa5ZueTKcTDFT/qnQbMxi9WbA9pPbma
            KrvrwslXagFjWfswVdnZCWka5CIA5jgMxsoPuVdMs+3PSw6KOEp7RIC3AG5OTMV/
            xPeV0y9KJLCB
            =RwMS
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
