apiVersion: v1
kind: Secret
metadata:
    name: gitea-oauth-secret
    namespace: gitea
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:NwuNh3I=,iv:vijvTsuOX8HPj4Q3hCwfDI2uvjpizW7geqdotngXX4I=,tag:7K2zkaGWNlcoexBDXZ5kUw==,type:str]
    secret: ENC[AES256_GCM,data:arSZFavXq+T727S75jyKj2IbUV2drf1qzsvs3zC360k=,iv:xt4Nq4K0HGp4i4nBbIfviG+4SDkw3Bb7b4S01HvrBNQ=,tag:5Lx/ZkFAyX3XP/d7uGbAUg==,type:str]
sops:
    lastmodified: "2026-07-30T17:10:29Z"
    mac: ENC[AES256_GCM,data:clI80sxJvcc3BU44iP7RpmIR+eY0zqnFDa+ayqIyqxxI1xUw+LV93QKvCiKUYQIms8mOiQinoufhv3apORU5eh+kynFfxiQ/hw7gFbTHZzngvRwnXTCEoV0ZQRjsWDPbyYvbrY2W+M+I37/Bs1yeB6iDWtqobwaSrQm3YIbT7ck=,iv:tFhgo9WNnl/1/TTvjLjaYO68MIc4OgrwnIj9JPrHCnQ=,tag:UmHkGHpGZbtSPxxd3OLq2w==,type:str]
    pgp:
        - created_at: "2026-07-30T17:10:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/+I6eCEL/drHP+g8D8WcKQv+nxG3T/PxcqwAur77B4F+wC
            jnmgXoWiKlxZ/0RiHsdZ2ZwUY9nzd9hG1J+PF+ZXHxuMX+e+H8OdOeLxG7XxvnHQ
            68dR8h8OOajc9W18Wbs4tdQBM3I1aqvBCnE7hWhZiSJGNeR+DRo9BPxKQ9dVvRG+
            WQxNukOSP5k/Ojs7IopUTjEOX/NODCxQficsgpwqBlQ9X+zZ/DSTe1bSpjSoTb0A
            tj78cfTtYuiXi0Ph87GRzeAsPPeGsJXWm1a+o5izZjI2xmq78hKDUZ1MQ7soPAYD
            dLVtJUq8moICl9F2KEhXDcvzfJtvC6RKigMW92lguXZR58Ftm5PGEmA489+FLvZD
            OWOuWX4Z2UMfrmlUbdglJ0qEb5i/itfJiRhGoxUukEHZ9nHu3hDqPR/H5Tt1MiHE
            3magRiLTWiL00YhFgS8muiP66XoiqdqkcH46iAz3ZcAQxASqIZ1QpXj366EIlp8Q
            GMIRlrd3+DLNaoTtXESlZyR7GQA1MflD7q9PBj697R8o25AD41Y/H7Nh+9aqbp1P
            dW1EtHvEcoNmSTlb6pX+LpAQqCPiJziNQdXGauB1xNE8enAtik9QiZLCu0O0AETT
            Iwg/rUkb5rMEkPzUMeP3n0Pi26ZA1asJJjHk/Z7UpCcNk6TXxELTPwItXGXon63U
            ZgEJAhA6tlLB23japx2UPwoWSr8quXKAeea/aC4zwT0QbVeGVYFH13viaXUe1Lzd
            aDubQh8SJRi3GBunF3Z6AoG2FO6I/FiMVh9Z+RnONcpB+6lLEe/0CyRBIAvBFNcF
            kH5cqG3C2w==
            =Ulq6
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
