apiVersion: v1
kind: Secret
metadata:
    name: valkey-users
    namespace: gitea
type: Opaque
stringData:
    REDIS_USERNAME: ENC[AES256_GCM,data:2S/6y+3FNA==,iv:t00+n+UWmCKMDRkjiAzqcNHD3RCUUtFD0bhojGjRN6M=,tag:W9Jp4WzLhyFcyX4XtWr6NA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:W5ESgP0amguL8+gK,iv:erGN489o4YLdZ+hsE5+nEC+P/hMliP7SCU1/PFTFLg8=,tag:w12a9OBi5/XEg12tWw01qw==,type:str]
sops:
    lastmodified: "2026-07-30T18:10:57Z"
    mac: ENC[AES256_GCM,data:R+ls757Q0zo+GyngNt+r2M1Lw25cw7r/SC98hyCDFSh87g2OloOlqlLtN7NwJbI37TS9wwbs2JAkkqR2XpwsvVkK2FLghaUMuWqltRpQePL/UMcYkWUJ+ubLrPSeMuZi2Dl3j0qi6Hgrl0caZdI1QyB0If86e3JM/OYY8qOy8fU=,iv:hGMv4gQIhPDAbxLhIO28aACIODlc6ugdxinHNeISVvw=,tag:1MTFD5kmplSv/33ufyrHQg==,type:str]
    pgp:
        - created_at: "2026-07-30T18:10:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAlRhHt4xRQ1xG+DzizNVrusIurfQK1M0C6Zmw0w0Ep5Oc
            F6DS/sJ3riGxKIIqEtliHc5fgg9/x4odvG3Ll0y3mIu2siDiV9ATf3QfXctTQX/t
            SOl+3XBGeBsmogW0dD1PpeYC+sxxjo1tlLA7KkJgaGuoy2q2IKZ7O1Y7JAPJ7XrK
            azWEqYtQSn8iCqFjlrSTmW+v/qYFt2CkGrbF+uKZXYnRoLjIwdczFD2aHItc5qRk
            nzZhyGwejPatgvQmrilpccEXmU4rl/sRC9KnFsH2cLyH0/JkJ7KNtnV5FqiOC+KS
            Ta0qu8AEnDWfz7yRMSBkvvMPAY9IuLwBcRQaTisQPyLz6XoOw4gQ2Cq6KHVReuLR
            5wf6ZiEfpReSrfwm2sdVM0h6yS4NLk+Ngrde11I5LQlUwkVSlEGQ7LcpfU8XMPWn
            1YngzRG38g1CzOi5SnRWrcCQpWuf7fksvGyrqHLlbh72H2z3yHVPj4mPfRevmgX1
            u2a55ytB62t4nSUr1pRMIagChYq4PmUCpT9zm53ZFBniU8W0iKEMqUg9ouMZ9LHP
            YHthS21twn87LW54xA+H+UjIReUF82kdWp2NFFSXSHw8sIgkuxLnwUiopwnUjFZ7
            Ju6EIusJLPU1z4f2oPJf6Pg3B2kE3mVdRiTQ4V5MfJyXSz8RJxRk0ABq7eiN2tfU
            aAEJAhA1b6EahJbqvR24Dh4JaD0+VYXgP8PpyYtNBWxZViAEEnNoJliP+fKf3D1h
            Fr/Cza1GY76+0uQuMiCE23yUKgEAt0xmsqVZyh4vdA3Ta74+ISpzC/aJVy2sEc5M
            cPzucRJei/Du
            =+3KA
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
