apiVersion: v1
kind: ConfigMap
metadata:
    name: external-dns-config
    namespace: external-dns
data:
    rfc2136-host: ENC[AES256_GCM,data:Dpl7B1LOi2k=,iv:0BAZnfZLOzcUplxILqA3nkwfyRJ3/U8EhXijMmu9XEA=,tag:uq+UasD8ajosQmxnG0XPYg==,type:str]
    rfc2136-port: ENC[AES256_GCM,data:JbA=,iv:YH2VSaPSAdjEvIdWA0gnEKSLvvIHvThz9v5TllhbSj0=,tag:kABnEfWoi1LLE6gRQI3eWQ==,type:str]
    rfc2136-zone: ENC[AES256_GCM,data:BEFJ97yDtLawQZNhMTk=,iv:9oTrAJX5ntjfM+PKP06A+jufo98DHAVUvkCQ3PdoErI=,tag:s1APL7dDfpur0vFr4qBTfw==,type:str]
sops:
    lastmodified: "2026-05-26T09:59:10Z"
    mac: ENC[AES256_GCM,data:Nkwk/bBFdTev+cbimfFCct1BtrNTtUEu/TZXGOMMNAcWskMfDz3aqGnLoDOSwK6ezKPdx8ukkyGGwgPgTLBXWLtlTF/No36xOFUhZIs31zOJUgAUcF6CAuQZnB0nw+tkBjixrWZjoWSf9D10pycthKH4hH/u+kVjsMH1T03Wtuk=,iv:RFdhFLxzGzjqdOKKpPxmREUdJP1dv7x3pTFQl12TDmk=,tag:c2xusxsUcMRHkYCKJ4KwCQ==,type:str]
    pgp:
        - created_at: "2026-05-26T09:59:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//dE6gBgqVO1hLr8IDlRIluDh/bYWG/9d91iaZsCuhUXLW
            6gjcuijanwnsF1FRVgOJH/RhwXyDUUWn7D9+l5bLX3Li6Gcdpp1/6j9wN12Gntng
            eNTeAe0wC9TaqFWrpcxT3qkwzLgoPlmW658PBgXV3g2rca4VQ6zNZ3DGNZXpbuTj
            Clozd/ZEuujp6H6N69gb6H4J1YyEKMi/Nh0OXFU8qxX8MyisXe3b1AdiYPEd1S5p
            Fp0Nlmn3MHf1vqwArZzTFCZQJB6RRosvaiFaTHtvlVUvINJbzMIeiMDXbxQhv2BI
            5Xd1EKnBDwH/yiNdCgLQxrIJbeji3uLj+Y7UZj7++jXveOL3kmDv9AooZF1DBnQP
            Hfp8w4ZM/ZWIiMtaaKHlRKny7wjUwSRxSnDeeCEsnK2nb48gPpX8Z/c4YcVToEDn
            XIqLA3ZQNdAqoAFoz0uqJvAJFBGDN5BCDXB0OSfO8jhynYcOvYZz2kaflq7kRBMq
            nTsFnGcCqhWkAhEkkYY96H/NuzdYrTDP7g/ih+rj6gEJTiRKGFCwx8HmG5ceHnfD
            Em9FZx9tEicw2wA35limaTLdPKmf2SKaXubgiaZtuAGei47404cw9ZVEL1Rseyep
            ib35JwNzFCukqbPljOBylb7xKtaLSIHi1r6S0P16abmS4IjJUcfps2tJ1DfS+dLU
            ZgEJAhA7QccJDS2ZI395DNSXaOnaBhYS29WEkRe6gKhaxrzecpjH8aQ+w6f1Ytl8
            ztwuDUXMJ90uPihiwa8VWgAwKAQ2VGYU8tDosvISiLNCiaoHD/2vHbOrYziyuTmP
            rwEod7HqVg==
            =HW9M
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
