apiVersion: v1
kind: Secret
metadata:
    name: external-dns-tsig
    namespace: external-dns
type: Opaque
stringData:
    rfc2136_tsig_secret: ENC[AES256_GCM,data:R6F8eKbxGY7iEd1dIULreKAMNGQpLUkzA9W1/+8EUFfc/T8cV4pyvbj8DwI=,iv:nVBoOUoPdetp9/x6zPjMpoobxA3E+xzR1z+4UyKx3uY=,tag:OgO9XqH+LvDrAhCFXe/GZg==,type:str]
    rfc2136_tsig_keyname: ENC[AES256_GCM,data:3ntD9HLGasDDjdn/Mp8k,iv:2zMH3essrq1qKa7T8U9obOGUNYOVmOJfX60MwCuEYiE=,tag:qQWiGemx+yIHUladAhgjzw==,type:str]
    rfc2136_tsig_algorithm: ENC[AES256_GCM,data:Zg8gD9X/E8yI+FQ=,iv:L+IiTUzmyx8Y/8Lp4foo7IvP3uWNNf4T0FpunhBkZi4=,tag:IW9I0w7mExxLxrBFkVLO3g==,type:str]
sops:
    lastmodified: "2026-05-26T09:59:20Z"
    mac: ENC[AES256_GCM,data:jXao/lluLaa6V9UkQYA7ZnGYo1uMKyQLhCCQOMiMxRgdzv/s4M4il9D80PFhmcIDYPXyrvLGfdw31cpIjeUOLAm5CTAooD8cvnjZq96Jggnz3NnBSy0S4jsg4QQEWZDoef7r+LW/bR6W7YlWCxugYhNRjQBmJsJpvDglWbAv9n8=,iv:HzcA7yCXe2e3Ahd8Ja4gTZVS+Ez0jTMldkcyhWDQiu4=,tag:7GGwsTHLYAgAWjxrHKUNCg==,type:str]
    pgp:
        - created_at: "2026-05-26T09:59:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/9ErNBPmGXoUHMLrJWkn+tfuUT5+fN/BWz0SkL3CxMK56E
            eByB9fHDWuUBoyCPkUu1AyTMHb9tbXejIGVkIDgDNy2wMyGLub3lVxS2POae3BUf
            chyuAazxjaK/oi4A1HqeeG03WcAFwpYQyXYX+6+SsShQ9wxfBZVkB63mKwmKgE/Y
            5YH+/bngEjZWcQby4FV4Q35+CPmDp2DVLsJ7hil4PLNHYA7XYlPNBDj8jCUQJ+At
            biH+Qnzg02UIWMpwx6oxrCfWiCx1pV2dlWm20UweLFuc21SJ7UDCyykdjw4jGrH3
            5D8KkQFAworSzdmPmavHXT9ORuVDErYkH2bxFIzuhLQNeTMgqZ+0ozbva4jGB6rh
            ng3/6BXlLI45wEKu7iRBj7tAV4p7nSv65mVHB1Emu2hcqj4U3yqt3K2kXyNIwGi0
            IaHgjHZi0Wx3MbjfmDI2qRC8dRiZUCt1c5QRXADtGBhVirA/d7g8BpTVhZown+Li
            GkzNkiUIhvJSH8rc1lo5aAApym5wPJ/dWEuNcAJtN60ua6aZVjzd+MgHsQFqOr2F
            tnCIDojtRosGcwuGXLAXunlR5Elbc1fZQsxNSjcnnZVAHHQcxTTnRlZdkoXc8rYq
            SEwDEvJbFPhnMyNLMuf5kHyhCNsf/AFEx/l7O38/HlnhDcUgQ0BSV6lm9Xx2WkHU
            WwEJAhBWGknZh3ncF+yMCGuC492/ooZTs6oegGOKChf1QlnRrv7fWtpkUVXq8wVh
            JkxDRbfRj6WaB4PfKllRszgcrOaUFlGBGh8DP5+d2c1qbrPaiuNis4hfZYU=
            =//+4
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
