apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: local-path-provisioner
      version: 0.0.30
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
  values:
    storageClass:
      defaultClass: true
      name: local-path
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /opt/local-path-provisioner
