apiVersion: apps/v1
kind: Deployment
metadata:
  name: fritzbox-telegraf
  namespace: monitoring
  labels:
    app.kubernetes.io/name: fritzbox-telegraf
    app.kubernetes.io/instance: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fritzbox-telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fritzbox-telegraf
        app.kubernetes.io/instance: telegraf
    spec:  
      containers:
        - name: telegraf
          image: telegraf:1.38-alpine
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: fritzbox-telegraf
          env:
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: fritzbox-telegraf
                key: influx-token
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf

          resources:
            requests:
              cpu:    "50m"
              memory: "64Mi"
            limits:
              cpu:    "200m"
              memory: "128Mi"

      volumes:
        - name: config
          configMap:
            name: fritzbox-telegraf
