apiVersion: v1
kind: Secret
metadata:
    name: fritzbox-telegraf
    namespace: monitoring
stringData:
    influx-token: ENC[AES256_GCM,data:ZkS03MA8dRSKjJ7TN1ipao6ez1O7+7fksvZxTYcMI6qS0U63/ztdTxOIA2zIJ+xhOIgoScrUhZ/OcrnePgnlysbrJb/uvw1rm+7aQtz1XfqRATwQRrwEtQ==,iv:ckd8Yq1g0ynbxl7fUv46268EBwm4hVyPZ2EW+mRh3RM=,tag:VDG98Efn2rkCShSMOlX5uw==,type:str]
    FRITZ_USER: ENC[AES256_GCM,data:5evQJnbd+70=,iv:B32SOjCuHc3ZRPd0ioFefQdpYy1D3WOaH0DaLVcbfhA=,tag:TasLJTB8D5rD5MzWyu971A==,type:str]
    FRITZ_PASS: ENC[AES256_GCM,data:9mDunn6UZHRo7qnwD9+nN8W3LMM/ssPPQ2RtlENz,iv:fa2lZElsdlucAqiItiIfx/qWayHd+k0yfHcix/zXZQA=,tag:aXT1jDY4/L13zBbpf8rr8w==,type:str]
    FRITZ_HOST: ENC[AES256_GCM,data:kvLqGOOO4AmTWROm,iv:VIJBD+dnZXg9ltciRFqu8x1iYPfJ9r0tkvRgdri4YHY=,tag:RKxqvUi4Qxy5qg2ClzpE5w==,type:str]
sops:
    lastmodified: "2026-05-10T10:40:39Z"
    mac: ENC[AES256_GCM,data:kpPcgp8AFstSOmQ/zrblH8j3eUH+ACVcLeWyqlaLDdRBqqlzqV+gHoFxE7O/MiPxk3LoNG95instK3RNTTam2NPErONqq/diaYaWHqex6otm8VuatUhCk5A+HPaDD7XNqEnkUO1erjp8m5B/m8WApweHCMqGZr2veCMkM8TS4Ys=,iv:Yln+efjKGEKuPOykoUSi4LZa8QpeLiPDRRShd7bQSbE=,tag:zqZu7C0DHRnwzZoNyFaHuA==,type:str]
    pgp:
        - created_at: "2026-05-10T10:40:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//S8OS1lqIHm15WFpwvQUjWJBeu3du33W3TX0Xdqk1EmaP
            zAYXa1NkQtlGXnr9E370wDJpU/2SzQ90vhDk7fkbS4GgdpNvXJMS98TY4vHYW7lE
            ZYuUvtj5pNdpdPV5htGmI7AE9W7tcYIa6765zuIjfKNAzdh0nIYIQYreK1aRsj/6
            5dbcX1OnjqszmnpyOOIYF1aVo3C7W+zrOm7oggWw/PyAXxdetltFFuo/gCUYdC4E
            QqeprHUIC3/SzKzoDgHih9jbF31mJB3ROBFvlwedW+LbF0AnYBsytoerLa6C8CZf
            3Cmr4oiaqko39SyX+kWClkaHJXZfgEbb5FEg4L/0ldFoIQhkzuguyDBDIl53d/tM
            RJxjfko6pv1GSAyXiBNIXn+HNaprgsTq3dwY3CreNJefTi1fEDHfVOEdpjnWb9/c
            /+62gJdpbMj5FAHdPF/vE/K0mArm1iCGFLWovjM4AV4NnuOZQ1d93b3uU+4UIKhV
            f0QAzny8jkWu4twtjfeeqczcHMi4YyPFbEdrHKj23tjKcZmjC3+FKX7q4bLeEm7E
            JYC5iDLqWCwoaWz+qXHhPt3hGP5yjhF+3ciErdYcIS+eJgfOr2kqQhc9FjMN+X1v
            ZEnkkFqK0PZb+RNoUk3SaLDC1pRYfTk1NIRU91oNVaP+3csOVNHUBrGycjPuZnTU
            aAEJAhC4nqexURCU0iEbflu4f2UGJmFI356pFhnBHPiazCa4h5pM3nSuB5PLIrLW
            8nmec63hSsvgOZvDs0qqNwZvlqWtnM7mC3xcpObvbXI6RarAM0X6aoZ/DydZnmYF
            DsaWkV7hA3qf
            =eBG2
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
