apiVersion: v1
kind: Secret
metadata:
    name: fritzbox-telegraf
    namespace: monitoring
stringData:
    influx-token: ENC[AES256_GCM,data:AaOVXu8vk++H9F4uPPjMc7UwhJ+K8AD3Y1iS+Y4MpCvIaXL56nJWdNFp+NW5O3mr4aWUXIRNpwDOh4NPD7e671+svDwDUW2ID7Fq6nvMBOtIdXRlg7MRcQ==,iv:vu2q4RK/9cUmEwPpBPklv8aLEvn/3U34YWDgKwR4gt8=,tag:OjDsGlAhp/9tgQv5l7IbQQ==,type:str]
    FRITZ_USER: ENC[AES256_GCM,data:LYBAh87oIPg=,iv:U60IEUfGY1sbBM8bb3bF9OnUcMd1p6dThxe0bXNrI4U=,tag:HT9ZWkPPUaghcl0CllfJ8g==,type:str]
    FRITZ_PASS: ENC[AES256_GCM,data:oakkKd0UAdhF6YJl/gL0ceheGgJVkIBBAJgitaXS,iv:WpdSB8YWf7JrktZODfM4xusos+RLmebMnNHAuCCAhg4=,tag:tkvPqZGmPB30+U2TfMhphA==,type:str]
    FRITZ_HOST: ENC[AES256_GCM,data:YN+XENbBKJOPI2r9,iv:n0MJpifX3WcCwhtVUvc4YtFhholosOcwbp2HJOct/Ns=,tag:R8DJ4tU5GZelTNf8xtZunQ==,type:str]
sops:
    lastmodified: "2026-05-10T10:57:32Z"
    mac: ENC[AES256_GCM,data:r2nvhFXAH/JMq94ulzoZ4ZquCPwCiQZa19mX76h/HQagK8ncIwcE0TwYPboMIl19Cp7kvvvLRHoJEJyvCupk2NtbA9kUbqQLZr3ckdp90JYb+15jUxPgsy7UOtka/8swLDpyjlFkyRV8geVrUnBmGAjCtu7hVRX28E9pmqGDfSk=,iv:glmgxqQwTuHurDUhj0lv+YWjlPHGFBfaob3vj5kE/4A=,tag:xy/NYJIDJO45ppsXcwHWDA==,type:str]
    pgp:
        - created_at: "2026-05-10T10:57:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//ZchFG2pmmlsTe2ex7SYR26TS11EjfozuUrsu6Nim50ms
            H6TsX0/P8+bf+F2RVAFIm40tU+ezW9uDjSVgdpI71Y9ssqlh3OwH97xEZ5w/XEbD
            L2hWz84HGP4WnS8wNVzuf12cdg+fa8s5krTZ+DCNyRa+kZftu7WbcDvEw3EKcmIx
            jy8ROtI7W0IHZQxTICb/wqKOdBagXc8QLzMFCAsEAqJp/v+vfKNpzuKhps6nCFKP
            cdRQwlGTTn8o6jW+bZwRRWQlRvTig41YifWxiTlvGlkZz9Vz9frI+7k5Z7cgFap/
            S0PTpWORCCp2kMxMfrgLiBaHLWrOvdHEdkcrLUiKVKFtcF6J3oPtEoaf4g4zh6gw
            ZQyTlEJyjpX/APQjZ7BRARduVmMfXkAbZt/XchUw08N8WL8zBZqHg7L2rZ+tV4aL
            Nxx0AiL0N11/LrhYJkLQqrYAKP56v/JGbShReGm6zAjfyvdS7c5WsKlDjawFIafM
            5KeRTauVKsb1UQaGIUljuGtnGDYc4pa+P6nmQaaHBvluFNsAz+izze51wfXZiWFq
            I2ldvwyEEw73X7lC39imQbrGIb+FjCf0lsPcifSHHXsKL3ACkktY1Ub+8Tvwbdja
            NpDRUmCNyRYeMxOsmJved0vuWfLN0vv5/eBynx5V+hKIK151IiAAwPa692Nl7+PU
            ZgEJAhA+pVdjUbZPhf6BCxa2yZrCD4CHmcVkiOGOb0RRSxCHpeD9WjsuCdE/cIUm
            F8IyPLM5gp260fAmih1RmbNEIwLTucRsD6EPCVHIM4iRGQewKOuIpcbH0WqVm6TK
            S/sIfPI+Ig==
            =0jnz
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
