apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository_ceph-csi-operator.yaml
  - helmrepository_rook-release.yaml
  - httproute.yaml
  - helmrelease_ceph-csi-drivers.yaml
  - helmrelease_rook-ceph.yaml
  - helmrelease_rook-ceph-cluster.yaml
