apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ca-download-https
  namespace: ca-download
spec:
  parentRefs:
  - name: crulabs-gateway
    sectionName: websecure
    namespace: gateway-system
  hostnames:
  - "ca.crulabs.intern"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: ca-download
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ca-download-http
  namespace: ca-download
spec:
  parentRefs:
  - name: crulabs-gateway
    sectionName: web
    namespace: gateway-system

  hostnames:
    - ca.crulabs.intern

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
