apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:8ZcMFko=,iv:4IBM1GJkFaUXJp/ch1CN3X603ikA3IHpJgCxkgRAkLA=,tag:XxiSBoZj1fCaf1HdM+jjqQ==,type:str]
    admin-password: ENC[AES256_GCM,data:vvoDI5SFhv11R4KpqOM=,iv:LbDoUoOHZ7YQJmHaeY455cTp2VAIUEmlkXk1HTo+4ng=,tag:GNBquTY88QwTmJsujNyNRw==,type:str]
    username: ENC[AES256_GCM,data:84jV,iv:9uEjMoLdf6BD7qXMAQWKdlXUsbma+N5lxN5qYQzv9es=,tag:4tiXCrH6mS8rNSliEgYMEg==,type:str]
    password: ENC[AES256_GCM,data:5czhuX5xXS04g5fSHZg22REqOY+cWDE9w2RWtx7L,iv:QKjEkksDqXj9zMJrNQFMXvclvoKmpjK/OAHBUfhuY1k=,tag:Xeg+B9Br9mFzN7TY7Fzn6Q==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:+GBObWn3hg==,iv:09dR3tprnGg7Qzaf6MrHTw0yI6BH0fLIpN1cd1Pi2Wo=,tag:xvitrcnEAVSRWhhDkWQ0dQ==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:yjR92YQaQSsRrvXiJa3dpjIMa1xvVV96Q/85VcQNNXQ=,iv:P+THwC2s06tkQmIkzkhW6qpBL0wdMJzrAFt3f/4daZM=,tag:a2hhTgAABjyrqIudo5qWEA==,type:str]
    influx-token: ENC[AES256_GCM,data:RneUOIXCRKtbf+5HKVaFDFSEEPw20IlGDWOOxA6dG5S86bwUJTc/nUqEp7S5psEhaF0A4rkfY6Zklxu76EGBWpLMp3LCosiTjnVoJ8a+Xfb2MFDZL0ZVhw==,iv:UY+aEWlpY2ObEmIcWG+cf445W8yV3cpGwwQIwTfsjvQ=,tag:sUhZ6WmGQxK9ZA4rAWoZQg==,type:str]
sops:
    lastmodified: "2026-04-30T15:37:27Z"
    mac: ENC[AES256_GCM,data:5FeHrWiuSOql+IsNtVh7A3Rj54P4r4RDEL3jeuPZiuZyu+wGRzCKvzQJPT9QK2yUhppoCJzEOfXRNJB6flemSrDG36ODpyols7uxz9/mvKPO0OQpuRulGEwfnSkVGwnzdsBApqxwIW4kJkARJiNgA4ysYeAg9MAHSFMTDo+wd2A=,iv:vV+x5T3B6J00D5FkO1KslENS1Li19PtI1Sf6DeyXCaY=,tag:Kj2AB1E4yGUEpDIUkLwnAg==,type:str]
    pgp:
        - created_at: "2026-04-30T15:37:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//RAvUawpj0l+8hf9eHdYugQxfgFRt85o0kBJyWDkZTz4k
            7CAkk8sIe31g3b2BGxRfVw2TpW2vYBVPvliupAq3hYH7/trdluzpPUGggle+0JdD
            cCo6LjXinaqL5HzV4zM5Hb1dHJ4kSgAI8b1iH8yBBnFsyGJQ+adHUGVztZsM8aon
            gGj04LO2hfTNj/gElenbV80OMQuMKIYEla93sUzLu2rV0PPq19JboOD7qPPo2YS0
            2hdz8/YWv27YB+t6d8El2iV808WvNSJSCV5VxggInIB6vwcCTnv8XIf9XoANhLWO
            taqwFybm2HXEeaf8zCr+1GCTf03xs1381seAcXM1OOibwmMgnPJwCz/z5eBrf8Wk
            zV5rDniLxNJzwNBFKjnxFHmUoWB0yoLh3ILz4LZUYBUFNRVodHxMIPWgzEE5cKi0
            rGt4/2//li7qolG/lLBSghpAqbJBrpyI8fHznP1wUjZT27qno5H3Ifx+JCvZhqhG
            rKCs/1bST5VpBq+KiCfzPDI2BmLgemlqM0n1zw1t+qR34pKPZKCG7F96Fg84RNRf
            oSo9mJjgWMR0kSyaNsOMa/u7duD/OIdj1VQXhTue3uX4f74zo/Q45CPoKncTyozd
            t7i2jfDLmZjA7mkFQuNK7SJia37cU7tyRum+QPFruKKUR/+7y0yt/7i0yM5MqwTU
            aAEJAhBhCnw1++zkSatX+jx0ueSI1FOQJKbMcgjRQtv/JdBukRj2Owiz9cgF7373
            a/csOdVGec4zmOMYKil56t+9ttfU8Lq7yCKwrvnlkVV593eUmlODq6il7297jF6y
            6DTc7hxMQ0TZ
            =8l25
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
