apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      storageClass: nfs-csi
      accessMode: ReadWriteOnce
      size: 500Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2000m
    ingress:
      enabled: false
    consoleIngress:
      enabled: false
    existingSecret: minio-credentials
    
    environment:
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio
      MINIO_IDENTITY_OPENID_CONFIG_URL: "https://keycloak.crulabs.intern/auth/realms/crulabs/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email"
      MINIO_IDENTITY_OPENID_REDIRECT_URI: "https://minio-console.crulabs.intern/oauth_callback"
      MINIO_IDENTITY_OPENID_CLAIM_NAME: "policy"
      MINIO_IDENTITY_OPENID_CLAIM_PREFIX: ""
    
    secrets:
      - name: minio-oauth
        keys:
          - MINIO_IDENTITY_OPENID_CLIENT_SECRET
    
    extraVolumes:
      - name: ca-cert
        configMap:
          name: crulabs-ca-cert
    
    extraVolumeMounts:
      - name: ca-cert
        mountPath: /etc/ssl/certs/crulabs-ca.crt
        subPath: ca.crt
        readOnly: true
