apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      storageClass: nfs-csi
      accessMode: ReadWriteOnce
      size: 500Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2000m
    ingress:
      enabled: false
    consoleIngress:
      enabled: false
    existingSecret: minio-credentials
    
    environment:
      MINIO_IDENTITY_OPENID_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_CLIENT_ID
      MINIO_IDENTITY_OPENID_CLIENT_SECRET:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      MINIO_IDENTITY_OPENID_CONFIG_URL:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_CONFIG_URL
      MINIO_IDENTITY_OPENID_SCOPES:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_SCOPES
      MINIO_IDENTITY_OPENID_REDIRECT_URI:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_REDIRECT_URI
      MINIO_IDENTITY_OPENID_CLAIM_NAME:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_CLAIM_NAME
      MINIO_IDENTITY_OPENID_CLAIM_PREFIX:
        valueFrom:
          secretKeyRef:
            name: minio-oauth
            key: MINIO_IDENTITY_OPENID_CLAIM_PREFIX
    
    extraVolumes:
      - name: ca-cert
        configMap:
          name: crulabs-ca-cert
    
    extraVolumeMounts:
      - name: ca-cert
        mountPath: /etc/ssl/certs/crulabs-ca.crt
        subPath: ca.crt
        readOnly: true
