apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: minio
    annotations:
        sops.io/encrypted: "true"
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:TYVfmc4=,iv:NBj6NGpqmfhrHwHjUT3iVpgJjWP7yiA8DHcw36cwfcQ=,tag:xtatbDZ80Fhc5SqLT6SyFg==,type:str]
    rootPassword: ENC[AES256_GCM,data:KLhP2GLlE1olQV9Nxrxa9H0=,iv:ApgPn9I3PukVslx4kPPjgNHNO4F44FiMsdL+E7/zCzQ=,tag:SQvxZ2oBQtZcQF0Fe/U4MA==,type:str]
sops:
    lastmodified: "2025-11-28T17:04:10Z"
    mac: ENC[AES256_GCM,data:4iteUv0uRPiegQdTVpa7TzWBMRImUS3MKTafZheceGTAvk3hR9DwYx30C5yIZexg5ko37jJ9X6YnK44nClEl1T/bE4vR5qt7JBInzjeitfHaO7uQlikAeRlvRIpk5CLqoYO9AwEbAnwy3ST7aRBhQE+D1/KZ2RbBRGTjrJuFvwg=,iv:LmMmEgxt/xfAxMRVVIxMi+VTih8bskcFaYrVk/jf3Qc=,tag:Y9ARVtykQEQWpKRyUCN3vw==,type:str]
    pgp:
        - created_at: "2025-11-28T17:04:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAhTR2f2CFzmGGq8VU+TSHEawZIiuFkKVEALELebl/31zt
            gtbTvg0Umg0YjXutxhR54y01HOpfZEL6xxtso1ZL5Q0TB4ZwJaVKGa5KLkkA1Q7b
            EP9q4zK8NourAhHE5+Bu/2RRJbAmwxocIO2yelZnXtKgDNoTOJJ22SDZ6Ikj/+77
            GpTkCEiqAwFTzLOyhNA5oAEUa9+wfuc+srgn+02rQLpJnF+/km+BcCN9OY4FI95o
            P9xMMrSk9Dpy68TERrPIf5PBItDm6Lc6iFwAVSSGIPI2elRgvegqThbiafhD0YkF
            9XzcX92BhDbaC4h4CkPfK1hC1j+ZwWPCPMFGmKYt8JS6lfjL+hfMp3636mOljed9
            SkMJYOT4fOjAqVgINpm8JkV5sqy55lltvOUywXzV358oJJqp/NG3DYC2HL9URZP/
            TtfYOlbYUPtzP9Jv2p8hyRvy9UdQsW4WqME24x/TI1ZwoyTw+SIJwGXg91mHH2gi
            Cms1WyTByTMWv8y+A9gjx7tpuZfaekJs20+Pc2P3V4R/pRwMLXHzJPG44BTzXerE
            kTb9msjpaLXtGKEcEQIArS/b4QqPoiaDQklBe4ppSyiwnjo+0RDX+I6rkE/4ew/D
            lLdRnTS6+GtWOvzeCsi8QOXrDN7mWF9xbZASbS0RX0YzCnM77CVbtzbUPywfuuLU
            ZgEJAhAe+K5fbIvXVdQNF1djmCPwU/mejnqKzVlMicuBD6bmMcen7qVtDl64OaHV
            5Rvos/zDCXdAH3dvQIvNopU2Y3vnb6x+ndazTrhF+RbNcdW5Z6aCFR+o29i2Mjap
            4gQsu4ffDg==
            =dbh1
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
