apiVersion: v1
kind: Secret
metadata:
    name: minio-oauth
    namespace: minio
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:k+iTeTKfx8lzmaPFqa13gqYIiCPnx5h/cAp5gjIhbt0=,iv:7iiR8rr7kw3UONRHXHUvfH1TN8+5BuEjR9tTLkM5Sko=,tag:af1ArDkLdsx+QykOyy/a8A==,type:str]
sops:
    lastmodified: "2026-02-08T15:27:47Z"
    mac: ENC[AES256_GCM,data:trnjYoMgDlO3JIuKGd1eq9G3YPZIex/VOFvxngO8J4G3iz1zuLxKyEYuz2CcH8wyh1mXWfbeW7eoBoeQNpQRktt0qRyXnh0sVyR8zWfSFZ7VYKOSQJWGiYYmydGvGmSX1i56qsK5guLRrPndaO713yLtamOf+adwZYL71P17Wio=,iv:6nuHfvhi3DRXJhSZJIx49dF3hFbZAsb+eIM858ucEZw=,tag:kPLZxSVTx8Vmb1cNOfo8QQ==,type:str]
    pgp:
        - created_at: "2026-02-08T15:27:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//W8Yay+Ih1qt0kK0UAPaL9FbCd+LLvx0Nkwv5mxOXZZPL
            zW8gGNUojb0G9z/4LjdLuxDmzFRs3SgPcgIyD/lk5V3ePVsY5n7jMF6F8q+MSbZA
            uXnRMMURbk5zRSUegcgY2W0JCL7g5fs9bRHMZioMLFnzgETwzovZrbVF9mkOgDIq
            dxmNhD76w1ONBdxRzU9kxXmmgN9N8WsfXULWMgqh6qHvGOktMub5ZnDQJzkZ4Kka
            d3Q9l4kELCEEjOxf1AK+JCQ6ZZ3LeHsLUChsbtZgCX1tTYjQmyQALADvpk22QL5/
            Y6c6D+qlQAd49FnVRoQz7eBV0+3vXtqu/yZ4J+5a/HF5HhZtkJ5/DwqHx43dNOTy
            eXibOOjzQvJHOWiOTyOEPMOHnn5Rx2F+SGMFag8pB7VZ1bomO4rto2KztN/WS3Yr
            i/iuHQouvYjld7u1gUWMdvCzBbLeRK/gEbfFQibqC4Wz+WosnQIG0uFQNincScmR
            m++njGB7F8Iq/v2gl3x8mp/PkAt5pV53vQGHyq/ADNJY2TyvAQeB9YyN2GNxRFMx
            KV1pl5wwwCxQnP3Pzd1Y3/8Q0zRZ+Yqz7mazI/6kwNxMwsTfC2GMi+rQ7EtxZtud
            AqLOz9gd6bA/uDbkQ4we4D+q7PbUTWvmtVHxSsDikRLENlKKY72NWY5dLO7IehnU
            aAEJAhDWH2nbqTciLYJ/MoZAlPdq5kVuYwqLVC6dPoj/IHiWsEP+Js33T3hsGgJq
            bWV/SF0UhJM5dLL88gpSIGHHgl0AQlcvCLv3UJid1K1q5AsEU2maK8jSHlLPus5c
            cCNodjc3V41v
            =Z4nE
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
