apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: seaweedfs-db-secret
    namespace: seaweedfs
    annotations:
        helm.sh/resource-policy: keep
        helm.sh/hook: pre-install
    labels:
        app.kubernetes.io/instance: seaweedfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: seaweedfs
        helm.sh/chart: seaweedfs-4.27.0
stringData:
    user: ENC[AES256_GCM,data:at/xXYERRftT,iv:BO3HwU5/pE+1DAzydOnJGt1N5khOSsUZuGfzuES0A0Q=,tag:x2+w4RfTx3GCi3Eux8CDMg==,type:str]
    password: ENC[AES256_GCM,data:fCTcesTy/SrhjuGMa+pT2dvh5J9Z8fNakdQ30BAK,iv:3B37HEOCtxxZmjju7EDX9jnrBIlRA92HxcF7ofgDZfI=,tag:0BLPW9Tx/71fM91jWfgssw==,type:str]
sops:
    lastmodified: "2026-05-21T00:24:44Z"
    mac: ENC[AES256_GCM,data:JGcC0FtzJe+gtEp+zJBHRkza+ntq1uZ54TqxVFBT7cPFVnUqpH6AzTvGJIxVL0YlgKdWoNb9kotY14ZKq4EZX7QBShrtVGCsGJGZSS5gYEXHEaw1dnO+44FGz7v84wV39hnAJ508EgmbLfG9GgHEdAsqRLWtgaZQ6V0kOizBf/o=,iv:hKY/MeNIUk35xyaONz3rTbdUQFqqF9f11SC0fsJy2bE=,tag:Rqh0zt7n7hu6ymH43jMhEA==,type:str]
    pgp:
        - created_at: "2026-05-21T00:24:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//YfiBR4iaTS8WUZK57vLc+XoWP6lkPSYWoelc8n+yx/e5
            x4S7jRU8OubR0t+S1/gruWAz7hA12BlN49v+lFLM+xAERIXUKTyT4omQQUV4D0Am
            EksYWH+UXeZOSudTrH7/nBAzsXnAybz4CgT8pIgMUInpk/MFPqz09bHkO3wB5txw
            jBj0rrWe6pNtyOQLPZ3EL8nnGv0aFsQtJ/YDRZmRk7b56lxoN8KTxcv7bkD/4RKw
            BdsTozY39eyeUHdYwigVbionb2ZHkutzSFtiD4aRCkdZQk+buV3O5T6S2wNjE3L6
            jS/HQiwUDWXY899SafRW3Ee2M5dUDoHId0se1hRZjIjH6fnIepw8al9jBMQLuoIJ
            xfwp20RiGkDuhP+4/hNWC+xspmxtcRxy/Qb2SxhP9RDF0U8wEO8nJLDh2ML3dlnf
            rEh1Ezx8qG5+fQzw0LtdTfsM2gqoni9Sp6LoXXFweWxDuNMnMXYiVgZmoF+1TjDB
            ezC6AO817eewgk4e5+TzeCXljGpvsKxge4sWxb1s6qU+0xv9RqhoJVCBZetPAfwo
            QxreFZENY/Z+B+ohI3AlceAS2rEHfCE+8DvzVNmuh2IxJqle9hVi8VoxwSRoPnI5
            KozL/TtGpwVDuDoltCekPUyQLtwdsRXViBGQTBM1+3sNarnZqrTjpqjSY1alVU7U
            aAEJAhCGr9xxsMc9HaWGjTDpCS6DLeVAejyaVA0c8cILcbADBBDT4lBspZ6hOyHG
            rSXDHCxfni30AXdvnWIxOW1+IlzNmbv6u3hcY/kUTJEfJtZ6vaN1rxXqXa+/+K+O
            AfFzgBn77mau
            =ElhD
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
