apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-db-credentials
    namespace: seaweedfs
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RQmg93YecQxa,iv:sugjZC7AxrLuqXoqWRpJz4gXtZhPXiodGrshDQfiz3s=,tag:BFkGwgg/sfg+r4hEqpwYOw==,type:str]
    password: ENC[AES256_GCM,data:tQJJpHlWLB7xHQHYk1vXeEBIfsDGeMQWKzcKzh9r,iv:p2ulO+K81jwXjGhTBDMEJNshMXnkbbysmDZNCmM3nTc=,tag:oPWPVXtlHUA7WcO4gfbvAg==,type:str]
sops:
    lastmodified: "2026-05-20T17:49:37Z"
    mac: ENC[AES256_GCM,data:yR1WyNmtYgOODEP7DAUTymkb47a44IDrQCJk5cFYQ+HlSJtbIiCmur0LSVUpbUkapLIccR2G25xROnYbjhNCQCTucaPJwAA91J1YTYCRxC5IUxaFKDlRm2MrSHklcy0iyfzaqV3SUSUgTS0Ay4s1UFfnxHFQ/nmIEHDaML/ToaY=,iv:sSsStj+FjzI1+ueK82DTpfKkJxGPijV14Al55s+XDs8=,tag:dAMe88MwAAogd+8RhGz7xg==,type:str]
    pgp:
        - created_at: "2026-05-20T17:49:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//XBJOFscgEPbNk0IwN7sPQDebRwJDP4WY5YgvhNhsYJnj
            WndOwh2ZTEmtiqdGo+QZ2dbAxIhNlnx1LPa27YqQj6PtSsErrjwgezbt3HqzzCnA
            UsNqZHXGP75pXwPqMxJnTT1yUCWAQHW8JXy4twLp+5C3gsAxVnegrOBwBPXWowBo
            O9T7PQbsUz3B4BYxOaUzx4aUb1nMJRSt4uRFL1ogEzrgbXMhlWFgFnJVDk/14wlD
            f445JcFB8DoUHZkRjnmZpk9K9lEg020EFP2SJSJiGQAwKranaWXg6nZGCju6A1t0
            Z872YO9VtxomJYqkQYLqwTdltjeVxfiAYdL0GVzcnKE493Otf+EoXnjchcwpyp1Z
            de+2RrnJ6GVEPHG4ed0OM/BBeQ6NQbgEUx/aJm8U/SiEx+IDLYpzkE9Uhs0Mn+Zh
            YEYmQbnQkNTzXwIYrchBzhGaUm/S30+ba3dpR0c0IjhpfGowYo6k1rrSTgyx9x2q
            gfTK3Agoaf3/rJD/frHDqRtGZI5NRh4nB8QxqX3huuwsT48b9aVc+zqtVA7/qaMD
            9WTCSplskME8rorxOonAzbjqeZDGFqLviehvjs36osOAEn0jwCLYP4wMirZ43J+U
            H2NIAmTm9HUA5yE8uatMOTNQXw3nq9xWS51OQ3rPWQj832mDG48ekz4+6WCQ1rjU
            aAEJAhDARubzI1XXbIQy2nelcphtzE8ECKkJkkdm5oaMGk+Q8OeyzJU5UTzHLJNV
            uSEohd600YqvG8GKR9KczayZPK29PvEk0884dzZwLFhDBnEvj8xgOE7C2aC/JtXD
            TerfvhHQ9Y4i
            =HD2t
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
