apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: influxdb
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:2kJjljUjmpl9KiIq54ZLt6a2O/qJEoXFmg1zDfCH,iv:q111LmNFX+nj8+NjqRSZiAbML/Yz6VAzcoDBT0qnNUU=,tag:L4PMxv+5TwZuzJSodupNeg==,type:str]
    admin-token: ENC[AES256_GCM,data:SCcpg2MmtdMA9HuDA7B0Li80j4wMrSV9+LWnVX7C,iv:RrW2ZTR9qx6WMfInpR90nAKBnsCYd/t9q9jI0JoiQBY=,tag:lG1g4fGWYmJqMgqJrfWlYg==,type:str]
sops:
    lastmodified: "2026-04-30T14:57:32Z"
    mac: ENC[AES256_GCM,data:haclRq/uicBSwG4hsBSh1j+OqxGbEaUtG5/28187RkVwtSUQdmSqCP70lu8MnednQM5Q5VPAeM2wkph0th6ljM9XAmdjpT/5CTV8IMqoqVHLtkOFkjhBoA7ig3eVwPbJGdT/qRb2XiRMrwJ4Gc0JlXkfGDy15SevLuPOu7Ve5Yk=,iv:DsL5h1Dw9cLMNedsnRsXieF5OQrO/iI+DdkGnLEb4IQ=,tag:YcHtN1MTdyzmueHaFV4S3w==,type:str]
    pgp:
        - created_at: "2026-04-30T14:57:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAq5LGlz7YzO188MJITSdTih1AKs5difpPJXIMP4L2CF++
            M/Wa8mBGBiANXElw9/qIFcN4n6xDMeHq9HYtplhndSPrre3IaTAGxvMWkRjOSVpn
            boD4ObhzPGwV3UERIhMiUVpPApANq51Ij+OuWgQPaby0P6TWH2HD5zTMU/YSwZT7
            7fMKVS3kYOlFe41Z84awmAkZb+z8oOOc3ygh5caKJSP4MESYJX88HDlL8C5MkZct
            35D76XQNJ/fI6SvsYLIWvYSa7DrqiRJpbs02H9iIDF3KizZuES8V1syvYPTl0CxQ
            aPW+bdROlYjnwDBbmtNWb1410JjW9zwnGS8sBq4CQzLyoKp2hBrqGnGjIazVT03K
            EhFRdYNorrVRGT+CtF8UWJlm9SIkkvO26x7AbquRQGVdOBzmzljm8OQkOtZPz4eV
            xbMwTM8JXwL/XwnymDbBZPuJVYc+xKUMB1ppF2XyoQYFT2aWWfY776rbcy2kZvDQ
            cOHRuHIxbpZvQWK1jA14GFTdlvsrsxtk87mQSGqrRemsXC22hFhs3Qs1NVp0vI/N
            bcKMc+RSV8g3J1WdTjmWqZZ18xGlwgJX76nFyUTTvmURyNUaodf/AXe3PHAQjm+u
            9+nEAPYO9wuztvTies3Ga1l6z8vsokIVagnp5DRj5XSqrGsdhb0jmrfW1mZiCoLU
            aAEJAhCUZ/u2R8bfEcu0qwlcFntkNa8I3MO96rIPOv8n8iA6/N8rsN98/4BEYIHK
            Nwgyp+/13HJx7kwFcLmHIdm0Xlz2y9+6PmABJ4RaJpAPSnK64119qUHwBz+miMAl
            8kc/rzkWyM7Z
            =2R/n
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
