apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: influxdb
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:l5o08+LIksNFWoqd5flqxSi/7xGFIswxqVdQ3cyh,iv:pHfgcUpTPtGCOYssTEuXSgy9DG5+ZNliTgfdqx4MdVI=,tag:azv6rASjmN5X1sPS2nENeQ==,type:str]
sops:
    lastmodified: "2026-04-30T14:07:11Z"
    mac: ENC[AES256_GCM,data:DRpXMGrSXv6V/xOGrmx7JcT9GTvSDrSx2ZStebrh6IvTAMgT4n9iKfmWZEt9jsAaVuG+8tjOwv5AnRjXcmzzlIw8uy3se9ZJpt1GHPTSi+uTHDqiREX2skrJ1WM1A8Fg5Hu9A+fHlqd5y4Ti5I73m6IGoojZTprWDUKlZZuVj7w=,iv:wg5u04IScMLQ5PQvGXIGWa/Txm3OuMIdrFemHHXgaZs=,tag:Wj9+xKtGEHhX8OeqUNo2vA==,type:str]
    pgp:
        - created_at: "2026-04-30T14:07:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//XM/mOi6+Bzy3/fTCNASugker5BRLmckZtQ4HvEXvKyZA
            vfDShE77SbRHKFFdmGrtS8yr+gv/4LzPAG5ctduLRaBYwFM8ykyJrPHqvITFr8fb
            5GDqgq5OrgkDrtG2zPxtrieQ1kWHvww261TS4dD13dGwbtvT3kf9oq1F6AMyBTgw
            RVC2b7AbFslNov2FCfT4qTIRZR834+Rv/ewP2/pLTDjMd3xOCX4imOT+yePUmsgw
            xjujJLw39Pe0cMaQCG4eo7d4k2E04uSMTEtC9Lq5ylHjDcVDmHxPfo2wf11nn5Di
            Qth8npMPb+T0mVjB1KQgpOVy05F6X0lmjTLxtZfGd/KjO7WaCF2IJL0TjDuBGfCv
            Zsvtoydh3H/g4GpPyBdMMBnq1WuDMaiDvm1Rf8MJsc2oN2yONoGNbNx6aKIbyoFM
            3d7qxguE8YVWTws+DhBqKUxvN6q3r5eugbmhnFJA1Am0FWWg15467vHwHTU1j71L
            hwsS9YuO9BrxrxMfT31iQnDBDhXdQcfK9vZMd23MzhIpoG+J+zWQBDxWjzl6s810
            ELdiHorUfX34jbTWWAsaC4n/qP7b2YN7RHPp9WuE9XWNzYGr2eBVl/h4Fj7buHQp
            hUX2rmuZCkfanDWGXPrF+NIL6X2Jq341ZR9Cs76ZQuqQqI+1tvuwMvaMcMdUJRnU
            aAEJAhBsdgNKOiXiLB5aQqVhuoHhGhJIYNzNNDSMQJhb3iP/PNLccwgjY2RpFSZy
            iPznKjxk6kAFIjIWpdrwSY+WkUQjJiJdv33P6QtzWJyKhk5z9QX9JZDMicMp9iSf
            Wj/ZZ6yc0bXz
            =6zzQ
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
