apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudnative-pg
  - cluster-issuer
  - coredns
  - external-dns
  - gateway-api
  - homer
  - karma
  - keycloak
  - kube-prometheus-stack
  - kyverno
  - local-path-provisioner
  - loki
  - minio
  - nfs-csi-driver
