apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease_harbor.yaml
  - helmrelease_postgres.yaml
  - helmrelease_valkey.yaml
  - helmrepository_harbor.yaml
  - obc.yaml
  - secret_harbor-db-credentials.enc.yaml
  - secret_valkey-users.enc.yaml
