apiVersion: v1
kind: Secret
metadata:
    name: valkey-users
    namespace: harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:KKfXr296f2YUgFAY,iv:ewRhcbYpgIGRMYNTyChB+XSOTtcU11MsIEHbiqfaK1o=,tag:e6b/5rwEAxUswI3txlzjYA==,type:str]
sops:
    lastmodified: "2026-07-28T12:39:31Z"
    mac: ENC[AES256_GCM,data:0+FqTBJ3tCs3YPrPzYZ0faYCw/1buHj4C35b25hAzOMZaKZ1eH+nj5d6wnTa7K6qxNb/A0NPvu82Dj95ilsTulWD4WpQYHVVGZ5CszmwBampcRuuDGLD3GAc+W7Y8I03qPlT5PLarKdpPYp90bXMEbHOB0R35z0wUxBiIjum41o=,iv:33mm4DX73F2ZN0INSJxVldCPpbx5AEclww3QFtvPduU=,tag:HdKfm2JszJ3cPeblF5Rtgw==,type:str]
    pgp:
        - created_at: "2026-07-28T12:39:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//ZW/ZFfZxaPGyGSfgzB5VNNSqa511dbuoSCmsN1vLlATX
            Jia7rrOKXdAv7Kc7wjzQQs44RCrlL6VHGtls3C2k/4hVMTm4+AFB5PRbqS3jSVHW
            qYeyUvk/qt29KuJzwHbNr1tCvA6sNPi9m4ySHjxxH5fnrep/66y2Qp4etyPGQe29
            sCNiNUpEeAWIwVecdT/AlbHURft8pldLknGXeTHU8E/CnPT7kl2dYEdknE5RKMqV
            S1PAj+mt9RNlWKA2QXycOo6Ut+OXpYbtOWkE2cIuZRRom+RHcLohZzEA/YOnOQ8V
            m/5M+Yi46JtLRsK4a7V5XTRqMh9gw6cGkDKVrCsZVl0cQjL450ez6odV4IEqE5oa
            v4JX4WHcihTzenxo/svY7uxUX2HXu5sepUTJPnRT2LzFRYEkPyRrhABeVhFK1YLV
            /W1soGssxunaZ/yEG8x6ErfujlHmASQTBTQ85RCMDdAesbgJi1P7IyPMNNQR/eeY
            YNm+YlpFVesCkv3KnqB5KsggzhHcxm248Eb7bUfB9x3/mtVJNP1wpYygPr8bbQCk
            h9KNbQimXq1tINN9BHQeRQybGvbEXBpVBdUjiynb7wKoMWj8URQ+RzLr2c+AHYM4
            Pyto0YseCPxhgL5zVa/EtptMJ54IkprcyXjFWgIE1aEjVVXZ1JNyPULxJzyEmN3U
            aAEJAhDTt3CHdD3fAFlb9AwLuBvDCg0EyQf/XnhET7MLoOX/nu7lCSumInTc6Bsw
            77aNeOy5RQva4eGJ5oW9/O+BthA1QYlgxk11DRA+utRGI2mtuqyejnAchkSp9tKr
            gxeEDowHlU2C
            =xGQe
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
