apiVersion: v1
kind: Secret
metadata:
    name: harbor-oidc-secret
    namespace: harbor
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wlAOSGREnb+6MwBz/RJfdK5N5CByXTvZB5ZSSHPQ254=,iv:fGClP+iQlYWVh7m9QVVxdUC128UdQmoi6PoAEyzPrDk=,tag:ANHi2gaCQVo5ltjsjhwfIg==,type:str]
sops:
    lastmodified: "2026-07-30T22:52:55Z"
    mac: ENC[AES256_GCM,data:4uQRXo33YTGIVsNWy/A6Xi2+5hz5Jobw+RKh3NOz+Xe5vNYdofkQjbGc3cKbT25b3tCXaX8zV7yczPc/8dWbHAQDGrCLzyCYzgT7uMUFhG4XtcqdETjiFVcwgpOsHRqg7LBUD7Q2GcCJ+c2gKTnq4f/XM3wrdn33qOb4k50D9Lw=,iv:Q9jH9BO4oz4Ns8J8rFB2P+zjZvaCrBo5aDlEM+7Xok8=,tag:Sf0ZambJChkp4qDWisu22A==,type:str]
    pgp:
        - created_at: "2026-07-30T22:52:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/+ICR5yy+XrwUs5kEc0T/+dbXzbwDm+fwVMYwL/dvat1vS
            y3t1LUDziFUYlwCiYxSVrBEaZC7FSrLrioXpcnhlgCMEKONLpD2aTXb60/FZXs41
            kQOiAI2EPrRzRRAEG0UWUSOvMLe9l/4qeqVIW4DwzrpL0W1Bw8yezwGx2SsMZban
            3Nj0YZc1A/qVKw2/JEzm1B/woY7buGRAfljptBZwBLmeOsal6M1retYdN+HwOXfK
            26EA4xeJdt213q/eMXu+b8tE4rZHoZq0xdxcKwRv884Rr8vyPpKvfkGuNbC3IZ2l
            KdUdz9YSe0mXEggCmWWfCmqFZ291RgKJU/fZ7KczP68gIE+2zEDZMUnb+9WAhjFA
            5VK+Kr1EEJ8yGr+4g3WUQPHZDBWqCyqgLq5mhhMc73qR5lwxp5bJc+2ygZFjro+c
            ypWhq/MMIMbS4DmPpaRu5hIiuukQDWZzDmh/P3TGi2fnipi9GppGfJA+0E3sOamu
            WRUzFkdx4Yd5r+rdMfvZIohrRalbkCwcNAC9C+EKqka7rFqVlDT43ViJ3dRT38zO
            DNq2ts8LI4v60XXAXZG2/EI0UY1UwJfyJSg+/Ebvb85WfHKrXFYADIqgtwQZKFY7
            q07gPjJiVNFOuYkh1IhMeqR3Mq1P6CwJ5ZQG5eE50xoRtK1353Y138NXRHjh+BLU
            aAEJAhAie9CRG3A3EpcVDL8Q05uesBUou650NZxoe55kAtyI6kLdaJfztnhzlDBd
            j5aobUS+2B+Hx9UhMxhu4EZv4Y2dbJG5Ef+kBC26y823t6ee/0xa2737eA7fppGr
            7lLQ5V27zllg
            =KtPH
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
