apiVersion: v1
kind: Secret
metadata:
    name: valkey-users
    namespace: harbor
type: Opaque
stringData:
    REDIS_USERNAME: ENC[AES256_GCM,data:lDvk2FLT6g==,iv:ZaYZuI0cgXxf3kksw5WS/q7n3ccGjENPgLVEV6xJeco=,tag:DlJDdL7oMl1nzhZglGOEGg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:6E5pHvP4XHDKGmMD,iv:jsMn2eTtxHMhlR1x7GAIQzj+n+hmV1Le4pdkLy9CO4Q=,tag:f1orHcaG/Z02gmtOfRduGg==,type:str]
sops:
    lastmodified: "2026-07-28T17:57:07Z"
    mac: ENC[AES256_GCM,data:J0wnBbuBcHt4yFhLWW2pdHf+2KhEb65Rw6cmIqTkPGm9wYaochnNtufpZXtGVeFbOhg4KW2a/J0AxH6deqd1W6WQ3Ezj9g1hWrlv0omzfmUtNXbDMFKp2bvOlbt8mjd66ViFemxxCrsZLNmta7jiR6MbunjtcW9wsKr+FA5jd1o=,iv:37YGWR090AHgFK6bFet9oi0iWf2eCUQB6xwPliG0UcA=,tag:5BczAwPeRpwTl1SxPZpQww==,type:str]
    pgp:
        - created_at: "2026-07-28T17:57:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAp8CQIzXypEKZvl9NoYSuA0g3C0fuXLOs1z/qsT4tpLnz
            a2EFtywEnvHlTn9+nMY22m4k0HSIdHC61ZgoEUe2L244zIr40Gp2rF07CdDX4/Xd
            DqHIGMUx3OSuO9jVP91KZjCdLGStUOKps757D2xlRfgNa0TmfyLkoUS/V33uQ/IE
            BiCPqJdupMVbfyEAes6yGnUxhTv3LIQ3n2mAiHgvF87dX/YPH/GBu0rVQeV+LOn0
            SvLqlZrhbH3+xP7CigI2Nso2iOiHSpp73InTyRJiTXDCsebErgdQQ42BU8/45/YM
            ot7VZxafmPZB9KmnPFYa8bf9O2OQate9uO4BdZHBe5qO0/ZBYviuPXtn2mkXmTCi
            vqeV0dCsshlDr7oaemtqrFFvK1YhNf56GjScLX7oUY+qrSHwX/a+KdV9moLEw9TL
            1ZAp++ZLmMCqwIv3Ic5HwMXraoUTvfiwOyYVrnxaj5eB1GN1IV3USlZ7bAeNVg7M
            Z2afrSq+0WaNnBqwM5vnkvWwODU8cGq40ElwUwCJxVFlvu3LSK65pPGgymc1gEKV
            pSWvAIGxMhMTDT9hHo26OO4NA5uM1RUz2+AfElU5k7wsIeX8Ru53WhuUNceUi/tv
            RRY3HzlSKH90T/VRxzvX+ei8yZhT/YWMRfQa1byAAPikssMpDz/GUyHrfMDhQi7U
            aAEJAhDq0ZXPFlzcjFHBydR4AlJJbr90dJGpwfPiENO2hvlJOQseTZGDw25uf5EM
            K5axyXnrHR87kwq3oGAUJ27LYBKGC1Uf7/5cFy7pKrOA6VTNSpMnrXqEXTVqF8Km
            YMIrntaTv81t
            =5Y2g
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
