apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-credentials
    namespace: harbor
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ucwU,iv:ebPebw1gm8J8x3gZa5dF6pWErgRCGEbTPSs/wwvm0rI=,tag:0idVKbcl6sfGhE0S8B3fzQ==,type:str]
    password: ENC[AES256_GCM,data:F5OBKkV4jTzPMB8fQ0X0PEXpfrDgUMib,iv:NLV8jCIu48SjVzMHbw2rnq9pbs5C55/N5QXSuzqT6zA=,tag:cAVQujoCw+cTICufnVLqDg==,type:str]
sops:
    lastmodified: "2026-07-28T13:26:43Z"
    mac: ENC[AES256_GCM,data:sihfaBj8TdYtw1L5+BreH97oq1Huc1u5ZdhA+m44/j8nocGTe37doxeMkBQNSkedfxGYTrso8v83g847xFk4D2ufRytzI8EuxzvvVC4OxcFU9DMkEE9V9o9pYP2SnDSxCjR2hm9s5l3rSdVdj42krT5EhcN4Xaa0QjPgqQCevkI=,iv:iQESLX2NWRoioPUbpH3hVXb8ScjQAThaUe2p6eQoR+E=,tag:KLNqUd/m7oSRGV/T33n3+w==,type:str]
    pgp:
        - created_at: "2026-07-28T13:26:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//atYhNbiSmn8oHC9oTlwqu7oUKlpeorLJgyoteyV7ggNB
            H82v4geukl3He93Isl58LWtXx2R5DFk4ux+1Avfqs6L/OHnJ0F1X4ZbgRHxBxfkv
            yo1khIlK4GtxHbwFd9fqq9vcrtQWGlBN30AaeXj8YdV/h3m/0vYe7w1hOv0RzWaj
            XKgjEPBbDSQTx5NG8RvbkV/yFsfiqMeDN/vQynT76AdNbVUTrsFFg0i1t2B6y1K/
            nwvuHHjTXpwvZ0Ub6A7C57LEVJjjRopMlHmemEEmt+jNN17qZg+TXHVLMB8ovu3j
            OmOj3wpO3d4sw90HCKEM0zdTSRROBkoEnf1daNWXeDx3rkyR0rlnnBJoU/CiUPCr
            7dqVxXH4bYCo+ZzzPH9/6UjVX8mRn5KlOaiCdB2Cd7Ws8dzgq9kOIDjcIYBOEnK1
            ihnQXbAdsp3NnEUzYBjCm3aCnGi2CrGnbXHaXGqHQRSKPjuialVRgxaEp9ZjUqEu
            CZsINXuYl+V2mrVhKNJEX+5iLPCduFpcYfOLNulDrXL0veUqO9BZN41nR64W2qwZ
            3hjdk3LWqSKsf1T1aHli9VorvqxepCe+CPYaIBp+C7iLdWupRH7K/3hceFQK6nRo
            aqNz8T0gyeHlrKkvp+11kynEmkVb3QbFgkKAXdYJbeDOyRQZG4SVWISwK72p5wHU
            aAEJAhAFfTlZux21Q94J9tVuJQLlMTRC0C18uMvZT0aBzcgXRHg24ModjdQw/UOL
            WKlGx/sR7mUwVs0c+5CDMyU4l9LlUfLxmGJ4EmDKyvXKB7Ym9TdukQgpURu5zkdX
            coW6CH1aDz31
            =xQxu
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
