apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loadtester
  namespace: flagger-system
spec:
  interval: 12h
  releaseName: flagger-loadtester

  chartRef:
    kind: OCIRepository
    name: loadtester

  values:
    replicaCount: 1