apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flagger-alerts
  namespace: flagger-system
spec:
  groups:
  - name: flagger.rules
    rules:
    - alert: canary_rollback
      expr: flagger_canary_status > 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Canary failed"
        description: "Workload {{ $labels.name }} namespace {{ $labels.namespace }}"
