apiVersion: v1
kind: Secret
metadata:
    name: zitadel-db-credentials
    namespace: zitadel
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ePDd,iv:00CpoWbtLB31m8vJ6cVjRGp9u3/1pSVyrs34juWURlQ=,tag:xYMlKXQEbMN9EokFMOFVNg==,type:str]
    password: ENC[AES256_GCM,data:0ZGpjl8itIQOuVoLydCa3SrlYbSCh9Gp/+XZtWGE,iv:MQPQzJwNTS6vkTcyEGAvxIBfzUNECLQlUZwKavXqk/Y=,tag:0nBE67DryW7MiFq/jC1nxQ==,type:str]
sops:
    lastmodified: "2026-05-30T14:50:50Z"
    mac: ENC[AES256_GCM,data:o9ZjCpWcfP0Ieik+g7Wl6og40cAj5Fnfq+FofTCxN4pNsx2pbvTcU3sFEIjIE6MTnahPRyyqTsQJvELFtjoxfK3eQlOzOaugGWXJcl3vtzYlPzW4LufEhkphhmOgVnSPMbUTShejWz0kU2y6OCMfold4eckYCKHPaRykLZ/erpo=,iv:avz/HTDA8LS4lMkIJhqKzh89+L+OqCV0PFZQIkndrmg=,tag:7OI0dZ3+PeqlSQYvUPokFA==,type:str]
    pgp:
        - created_at: "2026-05-30T14:50:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/9Hx4w2UTeBQkCrNA6upb80TzBAK1YU0hMt/Th2oC9tXst
            iqk0HmldjivjAabrvw+W/6FUUGEw2ePCm35zxf2xraL8b6uhFO9bnnDmL/9qpZD2
            /3HH0qEiZI4Xl/cRHqJBXhIVIo54gOdu2CGWeq4GwOqtfHjbGYHo0/BslsCgBo/y
            GsOWeGtOM1TcQEjsBbG5fXpOkE+C5AwVCQujk14Ob1ylbWybKFcXOEaewx9khjMP
            9GaTMKqR6SXSRPpmYFlogaJ6k848q6vC7A6Ga3RQ9dI4160cHbGjEgOeVsL+aOvl
            uikDbvBkeiNiwtza2ShdYF9c++GR5EKBhcoQI2FufYblxhZsA/KNiYPrdL5tPN82
            iqHU2SQXfkaiwGmCqK2l9NHCEjf6veaiPJDeKLfq8SATYv2rkrOUSLwb5vwjNwZm
            vTeKB/u51MoXrxNjR1nWotMGfMKkslr4M21DpZ6OgB1neKFUecGDIHs8Ey9R45wN
            sWem0WNFcW6KWjLCbQiWs4XuPlz9qN3SueePf97GIC+c6WcKueiTXFipu70Dwzzb
            eMaKEkBjBJIZtHlRdRL+OF/yzKyw/Y7WAvGBZ5mrutH8GOGgP4brmKhfpJqw3Mjm
            DXcfoMO11OqC49HVb5cwKvOxWgLHUN5YsDLCmT3dOA8mfQcJjG/YfLt+9AV3WtLU
            ZgEJAhCTWyOecLKdug24vXdjZr+EGKh50alOoAlHvGmk5oIW5Bl+UyP6yjPUZezB
            fChsbOYSVnyeBiyPB0NZG81rsyyrXyD1yApYFBjIrrPrpoRqVHq5eBJ9ItbkcN9C
            9LMRY0h7lA==
            =QZG1
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
