---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  dependsOn:
    - name: keycloak-postgres
  chart:
    spec:
      chart: keycloakx
      version: 7.x
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
  values:
    replicas: 1

    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-port=8080"
      - "--hostname=keycloak.crulabs.intern"
      - "--hostname-strict=false"
      - "--proxy-headers=xforwarded"

    cache:
      stack: jdbc-ping

    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: password

    database:
      vendor: postgres
      hostname: keycloak-postgres-rw
      port: 5432
      database: keycloak
      username: app
      existingSecret: keycloak-db-credentials
      existingSecretPasswordKey: password
      existingSecretUsernameKey: username

    # Ingress disabled - using Gateway API
    ingress:
      enabled: false

    # Resources
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
