---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/cnpg-cluster
      sourceRef:
        kind: GitRepository
        name: homelab-gitops
        namespace: flux-system
  values:
    imageName: ghcr.io/cloudnative-pg/postgresql:17.5
    instances: 2

    initdb:
      database: keycloak
      owner: app
      secret:
        name: keycloak-db-credentials

    enableSuperuserAccess: false

    storageClass: local-path
    storage:
      size: 10Gi

    backup:
      enabled: true
      destinationPath: s3://keycloak-backups/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      secret:
        name: backup-credentials
      schedule: "0 0 2 * * *"  # daily at 2 AM
      retentionPolicy: "30d"

    affinity:
      enablePodAntiAffinity: true
      topologyKey: kubernetes.io/hostname

    monitoring:
      enablePodMonitor: true
