apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: keycloak-postgres-backups
  namespace: keycloak
spec:
  generateBucketName: keycloak-postgres-backups
  objectBucketName: obc-keycloak-keycloak-postgres-backups
  storageClassName: rook-ceph-bucket
