---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  instances: 2
  
  storage:
    storageClass: nfs-csi
    size: 20Gi
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
  
  monitoring:
    enabled: true
    podMonitorEnabled: true
  
  backup:
    barmanObjectStore:
      destinationPath: s3://keycloak-backups/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: keycloak-backup-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: keycloak-backup-s3-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: true
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak-postgres-backup
  namespace: keycloak
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: keycloak-postgres
