apiVersion: v1
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:908xTo4=,iv:rCLnHr2IUA03TUidXOV0AiYwoYFFOK/LY5JobPxcia8=,tag:+7xsR/iJJBVUjFf5kABI2g==,type:str]
    password: ENC[AES256_GCM,data:Wx2pS+J8dHkPIQzUJsJY2xRB5hf8kobfWMh67aOW5BQ=,iv:CCZ0Z18DDSdgfMzDJnJdM9E0QVLVW8CsMXrEv8snCyw=,tag:UH4glGCFjEPDNT/uoc1Gng==,type:str]
sops:
    lastmodified: "2026-02-06T17:43:32Z"
    mac: ENC[AES256_GCM,data:SPbP0+v053pP8vzRhfJqAdH0H/ENWGnOvyvM0Sva/vNeLv54iJkkjfsO5yfnCMyak+3Dz3hQt7Du8aEfTQhmKtnnQdbDIJkbIgw/A2LbkPI4eGruAsbSO9o2NZN+8oDorDTXaRgfh/FkT1efPaOQ3Gbbk4NDa+gI/Ve14c4ON4Q=,iv:7RdqlShYtjuhxnbd5vlb6iien56p3VlEiS84BIGmL8M=,tag:7Uq6uV5M7AQMfBiw7ESXsA==,type:str]
    pgp:
        - created_at: "2026-02-06T17:43:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ/+KTfo3xml8tbEopCbL4uK5RWsp/0HKwnk8wtAZ3VJe3wn
            eVbsLGixth00WvykKHs/SBHrO+aE/v83elX/2Xa6iLXo45L4Sni7f+ikSBpuXHjk
            7w9v6F6J7fPTqAb04fnpLHRkTiD6ecI4T5GsDwcBFE0nP6Jonyt80y0wEzN8MheJ
            /MW4AHuDh6bPo6efNvR81yAnJ3i3h9RZDrLEIdv5fB72MmLF2HhKPVPCsFV1jCpY
            tgajg6tJb7JMf+wOqHRUzB1J1i99ABNqX+lT0wvQlf3z4wx+RRv0hpKLL6HamnfX
            +eiFmkb7Ny2x+klxHMLd4eFEvYaOxjSHrU22K8J/rwCXTXIz4IS6FxkP1qMKa11A
            2juwUs4QosIl4Sktg72RVt0NoVgNFBPllN+/8VepgLy1V6wBHUKB4cao7fC7G8Td
            RrPhsld3+weHsc5a6+7J7FTeo3td6ynr702Qmm4RKSiH58amXqXNlI7k+w604RZN
            pHvK9C6K9pJDagKtAEvxfVtShb43lbhVKIJYNaKSJ5VlvaE/sGhDuA2TjcGTqoBv
            tUEflpb+78n6qeUr7AHFG2xmbm0Zh019fTzN3i/pTljY0M3KWlub5hNZjZVN3SgW
            ANqrUvpOzEYGBN1344QOmmO+p6JJsGHtbMGWXmo5iMsu9xApyo5L78Zg2q52MOTU
            aAEJAhBOyv2bz6S2F6tZ+xEDFRXwQZzA1HjtM23zA6UXWzZUariP3m5eHkpCfGDC
            fb251DCZNqLcQyVJQAWYNnnubFZzJExqblIK1hygCZ1j/8+4XUbnfhEo9T5FpmV2
            j0F9Pw4qk+Ye
            =HH/Y
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
