apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: batch-https
  namespace: batch
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: batch

  progressDeadlineSeconds: 120

  service:
    port: 80
    targetPort: 80
    hosts:
      - batch.crulabs.io
    gatewayRefs:
      - name: public-gateway
        namespace: gateway-system
        sectionName: websecure

  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: success-rate
      templateRef:
        name: success-rate
        namespace: flagger-system
      thresholdRange:
        min: 99
      interval: 1m
    - name: latency
      templateRef:
        name: latency
        namespace: flagger-system
      thresholdRange:
        max: 500
      interval: 1m
    webhooks:
      - name: load-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/test
        timeout: 10s
        metadata:
          cmd: "hey -z 5m -q 30 -c 10 -host 'batch.crulabs.io' https://batch.crulabs.io/"   