apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: batch-https
  namespace: batch
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: batch

  progressDeadlineSeconds: 120

  service:
    port: 80
    targetPort: 80
    hosts:
      - batch.crulabs.io
    gatewayRefs:
      - name: public-gateway
        namespace: gateway-system
        sectionName: websecure

  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10

    metrics:
    - name: request-success-rate
      interval: 1m
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
    - name: request-duration
      interval: 1m
      # maximum req duration P99
      # milliseconds
      thresholdRange:
        max: 500
    webhooks:
      - name: load-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/test
        timeout: 10s
        metadata:
          cmd: "hey -z 5m -q 30 -c 10 -host 'batch.crulabs.io' https://batch.crulabs.io/"   