apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: batch
  namespace: batch
spec:
  parentRefs:
    - name: public-gateway
      namespace: gateway-system
  hostnames:
    - batch.crulabs.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: batch
          port: 80
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https