# tenants/batch/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - rbac.yaml
  - resourcequota.yaml
  - sync.yaml
