---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: batch
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: tenant
    namespace: flux-system
  values:
    namespace: batch
    team: platform

    ResourceQuota:
      requests:
        cpu: "1"
        memory: "1Gi"
        storage: "10Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
      pods: "20"

    repository:
      kind: GitRepository
      url: https://github.com/crulabs/batch
      branch: main
      path: ./overlays/production
      interval: 1m

    networkPolicy:
      endpointSelector: {}
      ingress:
      - fromEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: gateway-system
      - fromEndpoints:
          - matchLabels:
              io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: cnpg-system
      - fromEndpoints:
          - matchLabels:
              io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: monitoring
        toPorts:
          - ports:
              - port: "9187"
                protocol: TCP
      egress:
        - toEndpoints:
            - matchLabels:
                k8s:io.kubernetes.pod.namespace: rook-ceph
                app: rook-ceph-rgw
          toPorts:
            - ports:
                - port: "80"
                  protocol: TCP
                - port: "8080"
                  protocol: TCP
