---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: batch
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chartRef:
        kind: OCIRepository
        name: tenant
        namespace: flux-system
  values:
    namespace: batch
    team: platform

    ResourceQuota:
      requests:
        cpu: "1"
        memory: "1Gi"
        storage: "10Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
      pods: "20"

    repository:
      kind: GitRepository
      url: https://github.com/crulabs/batch
      branch: main
      path: ./

    networkPolicy:
      endpointSelector: {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                k8s:io.kubernetes.pod.namespace: gateway-system
      egress: []
