apiVersion: v1
kind: Secret
metadata:
    name: influxdb-token
    namespace: shelly-monitoring
stringData:
    token: ENC[AES256_GCM,data:fnKsJmrG3Hm38kMBwixnZhJeapeBEQGdflrnpn8nl8HtOnKVlivNh5gbC2haqW/nh8Dc4NnlMehO1S9ucPILz2fb5dPc06+8x6EcWhQev+nhG34j3qMNBg==,iv:BoTuptcL7zbKYRIcKhhVPKtfCSr0bmVSN54D/r/fx9o=,tag:3ximybFDC3O8vp12ZEIQvQ==,type:str]
sops:
    lastmodified: "2026-04-30T15:58:01Z"
    mac: ENC[AES256_GCM,data:hipY6vXFyhHKGDKa7TJQHzq6h6Sk0CDrnxZOf59dDvGbinlIGg5kE2A3b2eCZe5mjjajli5w4ypv5l2A83sZ/XMecKC3tHGmEFtkNFa5ykDMWNoK5HrYnjxhSwBQ57FWCr/t+2A6HDBoCyLohM/H25hFAYMntRegfdCuYOFcSJE=,iv:o5lm0TqVi0KgaX4hmcrQ79wOOcyOg5Fp5l1BTgFnPjY=,tag:oQstGe8OOLRhmM5U3i/eeQ==,type:str]
    pgp:
        - created_at: "2026-04-30T15:58:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAiTelxF0nhX+4kS8nSUBcF8At5aDLq5Vwftwz96NPAVed
            GJC9GgS+xF4eZTPecsQplsgjHYM9IWxdMIXGsFIPOjLeH8updXB5lJSOFuFSAGAn
            jkvU9hOKHc/CW6uUgNDO5KqKKGw23e3ZixDwc8moSXkceMTNJ1m+TgK9ui3Ps26w
            s1a9sRwdGEksLE9hzgYb0Z8+mxtYrqUQpULXjGc8Sx2yyonPzqyg9llfkYYy8Gu8
            Ltn+GXuxFPXbxZTg8/jSC0O6bG5CIPCf4LDp6KJmuJsHajEIhWrjZXC4h429M5dE
            CpkRcx0WW/ZiHRbuboRdSYTv1rYp+Q8ZijlN0DfTpTlklFEX3W0A1w+29HlHrKFH
            4uj2Hx5jbZa4gx/IZF0wmmcoRY84xrBtmzi8zz0PPqniLBsS/c2xQACLvYYCPqi9
            Vnr4Qb0yUOeRtoTQmkMgN3+1cnFmyYGYkNkJ7VEgpBgSCAbePp1KRe9zr6RJD5pu
            1MVwSXmoTrfXEJ7CFDJAyhiS+sk0jQfDPBD5wOR2fiv//GS4TXB8ITehFz9WWvfL
            EtvlDdmHkc3jdIn7vhdS9J1d7/poy0SrAcyM8Q5vZPMPslDLZNOYdG914rHFVQcK
            7zYdhpbe5gFAahCCl39W/08FlPvJSi9ZFZWhsrBS/nygnhj6LM9b6Aajzfv6NRfU
            ZgEJAhCOYahS+yJsZxhL36BJy4O11mgp8Zvp3IiNSlHW4pPF4WSD/akbfuFOMsZj
            Km7qKe1xOT0fl6wOtM1ROPmc7YmdyLh9Ej/HrfM50qkAfAK424rO6pbpSeAFvhFH
            9RxcMveMwg==
            =GEU8
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
