apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: '4.13.1'
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: kube-system
  values:
    kubeletDir: /var/lib/kubelet
    controller:
      replicas: 2
    feature:
      enableFSGroupPolicy: true
