apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: pve.crulabs.intern
  share: /srv/k8s-storage
mountOptions:
  - nfsvers=4.1
  - noatime
  - nodiratime
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
