apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelly-telegraf
  namespace: monitoring
  labels:
    app.kubernetes.io/name: shelly-telegraf
    app.kubernetes.io/instance: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shelly-telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shelly-telegraf
        app.kubernetes.io/instance: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.38-alpine
        env:
        - name: SHELLY_URL
          valueFrom:
            secretKeyRef:
              name: shelly-telegraf
              key: url
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: shelly-telegraf
              key: token
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: shelly-telegraf
