apiVersion: v1
kind: Secret
metadata:
    name: shelly-telegraf
    namespace: shelly
stringData:
    url: ENC[AES256_GCM,data:O5fkDxbxwbaTr5mM90BZ24chfExkF4GATHiOf8rZeM/tUjp3/E0i0hI=,iv:0KXM+RALSZRWlnvAjTWHsNzx4WBKh+z58D8zM4liCio=,tag:ROz5lf+COjRESGX9rBklpQ==,type:str]
    username: ENC[AES256_GCM,data:bYL+,iv:yh9PizY5ob1Qya0rPAvyo770lda2IyPa+UAIGugPIkM=,tag:BoOIiSclSNPXvgOVbqVlVA==,type:str]
    password: ENC[AES256_GCM,data:ZHWUQTA9MAlK4Ve3NDrzVRs8QnppmEHM+dXIWEhp,iv:tY6PVg5fOaxDrwQvp9Gw2VNOg0iHRSeNeV9eyx6U2hk=,tag:Kj2v34kgwcxDXLNiXqVwiw==,type:str]
sops:
    lastmodified: "2026-05-27T14:11:51Z"
    mac: ENC[AES256_GCM,data:S0gwJcgd0wIXe7BU0I1RC0Wtnmk/N4n788/BzL9ShrBY3F7546Jwo+Sz7B0MP9SuX3FCzIWRqmkV1byQe3Mq1WBC8r6C37cr2LA6dVIiA5IeV7h9yMxxHqhJ9Xw6wxR3FYSVuK7EQrqhYdRm1U8O3kO8hkbZURxTHQKDioLusN4=,iv:4sLv0d/DYLz8lDPC/Hc3URdkKYIQpRXjb6Z+fMDeqX0=,tag:hfmjIpJEpRn0PAEo3SKekQ==,type:str]
    pgp:
        - created_at: "2026-05-27T14:11:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAhPnu65Df262vmaHpkhjq6WIKohLvbNs6dVqDmrdl3BUC
            xXwqH0P72PDQUQCqonddVg4d9zNgPlmkzDGPpu2fg/PxWmhxe0IFW7HY4ssTmN9Q
            TW5xUl1JtW2+UJlaSnBWEisRg05O2IYUMbn+Kk9rwgD02WbeHc46jdFCsjVTW5Zi
            rqSp2JlVGciMb98Pt4CjBSjEqOFsPUJfCk9cHZ0YJL8NA+TFpCRuKui7ZVzOoH9j
            i3rOxHv9dJOCpMJ/wL8db4B5DRxDntjgW9fY84uSYMjD2RIxjEhnipaEntlxFuym
            ryvlNgSu8ckc2bNSEylykBzmNgkuI3DclrSHy12A3Dc9ijDFQpxfOzksvp9sztTf
            F1RqMHeUbUlth03NqL88v0GL1CvfwQ/9jeXIMAebUp+Py4UGH9YXgJldj0XNbKpd
            fmkrfyCOKFLCBnj6oBCgP5/F6DXyvxiC7azFklKtJbm0yJNsQFuiG14sfkJIqA1m
            rChwIo9kknat+gbw46mLkf3VNB3kCfEWHcjtZr42b9X7EtanQQp2nHBPFAfTbqGN
            bVgMS/jmQAAGCksuL6kGSSFBCtr0cyg87upNDzjSBxOzcyZwITYJpzMqxbjqfn6H
            gFOdw590F8zrXzgFPhAccfQNfggIZ1Wk927eKPDOpOxjWFFl2hWVlTtVzqwyLg3U
            aAEJAhBCi0RDeeL8IFwBRjwVq29lnMMb+5TJYJWGmc1qh/Ir/8+Pgpv/m2FVdKvL
            B/8VVSkeYIevJFIZABUwpxS9mzpSzewHRDLm+3vhMWd78OI+E8BHQtgKL+/Dtm0/
            /b7BbnGyElNg
            =EPV5
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
