apiVersion: v1
kind: Secret
metadata:
    name: shelly-telegraf
    namespace: monitoring
stringData:
    influx-token: ENC[AES256_GCM,data:Rxsn8LTMftbBpDy5D3QFfjGiT5Wc5rY0fCSyYmRQA7k3y+Jsx46yw7zlI4PqhSHWycEK+BdARFoXygCqwKtdqb2QoWDqN19a8jMhO5OyFf/yooiz8Dkbjw==,iv:xRSkBfrnE2vHHJvkgdiV4Q/aDn/nVK0z7qGdMkALcDI=,tag:pWpMpIhFx/BYo3JGsMcauA==,type:str]
    url: ENC[AES256_GCM,data:STJvRFbZ5nVWUKwoYGCV8B3Rb/OLTIGd/ihzFqEH+/ggS3Y3dlN8s20=,iv:Tl/meHx81uga4beF4Eq6uHi+hH1m+MuIYoLRhp18j/0=,tag:Hke5Hi273dI7MlK/zF+MxA==,type:str]
sops:
    lastmodified: "2026-05-01T23:39:37Z"
    mac: ENC[AES256_GCM,data:VIrjpSYRgQUCXTkCDHBER7QOACp+12toKCW5CXwPL+azxSGQi+pOTJx9ZE8ze9zdF2s51yE7QWj7gFR0wkYQLvTsSWCTHuTYrd/ggvQgP2P0Md5UVJr0M5wKE0EfForm4PGkX6JXJcHQS3IaGFd05cgn90JStfDe/QRiyTT+lWI=,iv:6PIbnMqcLCf0UdDhpxd4MqxRB1Ob6t3ZXD7lOVW6q0E=,tag:XNPqlmmgu2pFLwlXU7RyUA==,type:str]
    pgp:
        - created_at: "2026-05-01T23:39:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bARAAsgivJ14qsbz0IDZreuldhseQFmzFtcdG/YxlgU+AceDf
            wqDf7YPgEHLqZeW5ihLULzSPcBEYeD28pYGLNzF55hVHMl+xhrxSNpBvoPFiX5vb
            TMBeZQbg7+WL+pSdnAVMi1Q20hlz9teKpH0w64/w7q3JTrprfVn6fV7sDkxooMBs
            vUjjG/klvQJLwaBsRAdAoMecTcgD6RBkWUO+BpXVzH81mJN0jxSis7cB4+Q+BW/G
            9sY1vzQqYPw9wvq4b+igDcZ4Tyt33YmG2Zy/MGrObWD4byB3JP1k9ncqbIelM4kM
            gUIu+HGZpCTzMbO3ADtr3eX9A4zYbAxm3hygcRq+lgBVjR0x8vBEC/YmN5+1NG2s
            HvSSp6UhWC9o0DnCb6WF2cN3vNFqZ2Peuvy/T37e0VjAfDEUK32bnYRwdfQVX8X9
            3tIYTy8a+E77lR8x2qJWVTd5sYkB1hugdC3BUJnLKUXXXx/iUBZoCf8OiZ7Z0Bbf
            gCvypbYC/ds4TkrZEidxBsayuNL87MTqU7BGOyzuyhxOUxf+tdUnqcURr+gxJw4a
            SHautzbLGU71ErmplVs990L6ADx0UDjnGwHAXqNkgwwLjQZc13hI8PtcHVCMvVHY
            dTgM/iBKQ1B+uJoq9N2e6Z2k61Cv5PZGrrB9e+iB5tL70rCVCPMDRxQzba5goy3U
            aAEJAhAeT8WO/YiC1cob/SUKt0UiWeMX6T4h/B7PTBD06Hy7Xyh8bRbf7SkvGuAF
            u8NBZzLrrRE1L7+UqjT1ro4jyt77nt1q/209uviwdIJtKXrYQQmr915sSMo3mti2
            VyFbxTw/XZ/r
            =pUci
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
