apiVersion: v1
kind: Secret
metadata:
    name: shelly-telegraf
    namespace: monitoring
stringData:
    url: ENC[AES256_GCM,data:hhXFuEcPvC9uBmQO6UmDvqCBV1duGsu/4dyPGL0Q+Kr9HN3+fwrZGSE=,iv:7I4i+ia2WrZ7yIPJfn4bn4d6/27VzGkqJP3VGizNsko=,tag:5J35PBRXyuCzvfiaPw4p5g==,type:str]
    username: ENC[AES256_GCM,data:ikT7,iv:wDswfJp07QYrkVGIU6QNuEzv05cJI2ro2mBnqaydFRg=,tag:tRIIsOoY9Phkm9aXnGxxKA==,type:str]
    password: ENC[AES256_GCM,data:3BT7BzNVi66zANRPfKa9GMOiuPYNXy/hnpn9ZfMc,iv:5oBfrGqbHW+C/d3ewIQeMTcikADvionCB49Rp7fnqUk=,tag:GAn908QbdArpbTvfhg/rYQ==,type:str]
sops:
    lastmodified: "2026-05-27T13:50:39Z"
    mac: ENC[AES256_GCM,data:IqQtu/tKmx+d+5HHXXBdrxdLZOyxYw63yVrz6DzzbTXiY3nl/cCDw39KmzGz5hx6x3BAc+9zHg09T86AUmUnJa92gWp+ulDOyPcYYqsIj0QU/P4TMk0iIaT9NWOTYAf+ifYHQilM7cFghNAE8SuFjZuVzBFjxYxcKp0RRG1d/aw=,iv:UjO+p/LLExOFrHRil5+VhCojGLGDuFSo3FGGz4l4jLk=,tag:7eWqBfmAObo8hbZFOUDkyg==,type:str]
    pgp:
        - created_at: "2026-05-27T13:50:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0FBPlwYR03bAQ//W/6UI2a7utKK3iCrPIvVKp4khbqWv8bXjxbDf8BF99E9
            RQAyKleeqWJFjI73VtUxJcgtQR9w+L0Hlo0qDeO+8gsBWklzaCgxResnNPOWlUk1
            U6cJVRU1Ijz4psfuL9ES4mhMiHP6im9uJYZuNr1WjoO2Mze6jtVjdh5RBvtbA0zO
            amx/TbwPbLVxHQbd6lNr6DE1fnz0v0g9nQufeAC1FUIxWh8FLnVgpdUQr5IOZPsl
            5WXykjSdraixzNmMu5oGIx/3q33I3e/5SZeYrHMKPGCUzuCApEXczb99xHt0vlsF
            KWOk0IU8gJhLy3hYCsKFXZmXYf1L3l6EdXwRVaQsu/DOzTaO7u8u578N3CalGQXQ
            TjxsdYyJaN9ycYrN9af4sDjVc2Zk+Y771JN2i8WV4lY8HYRQV//C0SLwterayWwU
            zn2+AUswT8nGM+WfMEwlNrta6NaRjEkzqUa/qZJCe2hDTnc7JN1POHVEjk6oCGwz
            GnfFqaFjj7tk3QUof7G0jnrjyfdKttFJdMPacG1NTeIu9xGOvKzuyHfLkHlhDvuE
            BDd5HFCU9oxeGHm17wX/or6Z8zptqZng1apBcowgkpr05NnzHAJ6dbs6zHDIX9L9
            2rOk0EzSCqzxeTdV8HONL2ddHD5WPA6xZn/WvpNEwgE39dC3ZD7mHtlMDpulpPfU
            ZgEJAhDOpDe3v0J/iVk5v0AB6Czz8m35GNbX0L6rpuGDk7PYTPDLxl5Z7hk9a/1c
            qseIzK/lMYI/N6xx/oMVPcfTCaILDVrI5XQxg4JeyYyGxqp7q2uAy1WID1mKyRil
            gNOly8FOew==
            =CTcc
            -----END PGP MESSAGE-----
          fp: 2F45BC42327907C5B833A93041413E5C18474DDB
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
