apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: ingress-nginx

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi

      publishService:
        enabled: false

      hostNetwork: false

      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
